#!/usr/bin/env python3
"""Build one RFC/spec markdown per FinGuard feature and the specs index.

Run from repo root: python docs/specs/build_all_specs.py
"""

from __future__ import annotations

from pathlib import Path

SPECS_DIR = Path(__file__).resolve().parent

STATUS_CURRENT: dict[str, str] = {
    "Shipped": (
        "Shipped in the MVP: behavior is live in backend and/or UI with regression coverage."
    ),
    "Partial": (
        "Partially implemented: core path exists but gaps limit daily use or Vietnamese coverage."
    ),
    "Planned": (
        "Planned in PRODUCT_PLAN with a phase ID; design agreed, implementation not complete."
    ),
    "Future": (
        "Valid user need in the catalog; not scheduled in product or engineering plans yet."
    ),
    "Roadmap": (
        "Engineering backlog in ROADMAP.md; trigger-driven, not a committed product sprint."
    ),
    "Out of scope": (
        "Explicit non-goal per ADR/ROADMAP unless product requirements change."
    ),
}

CATEGORIES: list[tuple[str, str]] = [
    ("Transaction capture", "TC"),
    ("Pending management", "PM"),
    ("Confirmed transactions", "CM"),
    ("Reports & queries", "RQ"),
    ("Dashboard & charts", "DB"),
    ("Settings & profile", "ST"),
    ("Data storage & export", "DS"),
    ("Chat UX", "UX"),
    ("Localization", "L"),
    ("Phase 0.5 (Vietnamese)", "V"),
    ("Budgets & goals", "BG"),
    ("Recurring", "RC"),
    ("Auth & deployment", "AU"),
    ("Mobile & PWA", "MB"),
    ("Integrations", "IN"),
    ("Quality & testing", "EQ"),
    ("Payment accounts", "AC"),
    ("Engineering platform", "ENG"),
    ("Out of scope", "OOS")
]

FEATURES: list[dict[str, str]] = [{'acceptance': '- [x] English expense → pending\n- [ ] VI golden flow step 1',
  'dependencies': 'DialogueEngine, record_transaction.',
  'effort': '—',
  'id': 'TC-01',
  'in_scope': 'Single-turn expense → pending card.',
  'out_scope': 'Auto-confirm.',
  'phase': 'MVP',
  'priority': 'Must',
  'proposal': 'Maintain; extend Vietnamese (Phase 0.5) and optional payment account (AC-01).',
  'refs': 'TC-01',
  'related': 'tc-09-vietnamese-expense-chat.md, v-03-vnd-amount-parsing.md',
  'risks': 'VI blocked until 0.5',
  'slug': 'tc-01-log-expense-chat',
  'status': 'Shipped',
  'summary': 'Record spending in natural language with confirm-before-save.',
  'title': 'Log expense via chat (one message)'},
 {'acceptance': '- [x] Pending income card\n- [ ] VI income phrases',
  'dependencies': 'TC-01 stack',
  'effort': '—',
  'id': 'TC-02',
  'in_scope': 'log_income intent + collector.',
  'out_scope': 'Payroll sync.',
  'phase': 'MVP',
  'priority': 'Must',
  'proposal': 'Maintain; add VI phrases in 0.5.',
  'refs': 'TC-02',
  'related': 'tc-10-vietnamese-income-chat.md',
  'risks': 'Income/expense keyword overlap',
  'slug': 'tc-02-log-income-chat',
  'status': 'Shipped',
  'summary': 'Record salary/freelance/bonus as pending income.',
  'title': 'Log income via chat'},
 {'acceptance': '- [x] English minimal parse\n- [ ] 50k ăn trưa',
  'dependencies': 'RulesFieldExtractor',
  'effort': '—',
  'id': 'TC-03',
  'in_scope': 'Rule extraction.',
  'out_scope': 'LLM-only.',
  'phase': 'MVP',
  'priority': 'Must',
  'proposal': 'Enhance VND (V-3).',
  'refs': 'TC-03',
  'related': 'v-03-vnd-amount-parsing.md',
  'risks': 'Ambiguous categories',
  'slug': 'tc-03-log-expense-amount-category',
  'status': 'Shipped',
  'summary': 'Parse short messages like coffee 4.50 dining.',
  'title': 'Minimal expense (amount + category)'},
 {'acceptance': '- [x] Second turn completes',
  'dependencies': 'chat_sessions',
  'effort': '—',
  'id': 'TC-04',
  'in_scope': 'collecting phase.',
  'out_scope': 'Infinite loops.',
  'phase': 'MVP',
  'priority': 'Should',
  'proposal': 'VI prompts (V-8).',
  'refs': 'TC-04',
  'related': 'v-08-vietnamese-bot-templates.md',
  'risks': '—',
  'slug': 'tc-04-multi-turn-missing-amount',
  'status': 'Shipped',
  'summary': 'Bot asks for amount when missing.',
  'title': 'Multi-turn — missing amount'},
 {'acceptance': '- [x] Prompt then pending',
  'dependencies': 'TC-04',
  'effort': '—',
  'id': 'TC-05',
  'in_scope': 'Collector.',
  'out_scope': 'Default category prefs.',
  'phase': 'MVP',
  'priority': 'Should',
  'proposal': 'VI prompts + hints (V-4).',
  'refs': 'TC-05',
  'related': 'tc-04-multi-turn-missing-amount.md',
  'risks': '—',
  'slug': 'tc-05-multi-turn-missing-category',
  'status': 'Shipped',
  'summary': 'Bot asks for category when missing.',
  'title': 'Multi-turn — missing category'},
 {'acceptance': '- [ ] Description in chat + CSV',
  'dependencies': 'Gemini schema',
  'effort': 'S',
  'id': 'TC-06',
  'in_scope': 'Optional description field.',
  'out_scope': 'Attachments.',
  'phase': 'MVP',
  'priority': 'Could',
  'proposal': 'Rule extract for note/ghi chú; show on card.',
  'refs': 'TC-06',
  'related': 'pm-09-edit-description-date.md',
  'risks': 'Low vs locale',
  'slug': 'tc-06-transaction-description',
  'status': 'Partial',
  'summary': 'Notes on transactions.',
  'title': 'Optional description / memo'},
 {'acceptance': '- [x] EN yesterday\n- [ ] hôm nay/hôm qua',
  'dependencies': 'ST-03',
  'effort': 'S',
  'id': 'TC-07',
  'in_scope': 'Common relative dates.',
  'out_scope': 'Complex NL dates.',
  'phase': 'MVP',
  'priority': 'Should',
  'proposal': 'VI date tokens + timezone.',
  'refs': 'TC-07',
  'related': 'st-03-timezone-setting.md',
  'risks': 'TZ boundaries',
  'slug': 'tc-07-relative-dates-chat',
  'status': 'Partial',
  'summary': 'hôm qua / yesterday in chat.',
  'title': 'Relative dates (today/yesterday)'},
 {'acceptance': '- [x] No DB on error\n- [ ] VI with LLM on',
  'dependencies': 'GEMINI_API_KEY',
  'effort': 'S',
  'id': 'TC-08',
  'in_scope': 'Rules-first LLM gap-fill.',
  'out_scope': 'LLM every turn.',
  'phase': 'P2',
  'priority': 'Should',
  'proposal': 'Enable for VI beta; log usage.',
  'refs': 'TC-08',
  'related': 'eng-outlines-structured-extract.md',
  'risks': 'SDK deprecation',
  'slug': 'tc-08-llm-extract-fallback',
  'status': 'Partial',
  'summary': 'Parse when rules fail.',
  'title': 'LLM extract fallback'},
 {'acceptance': '- [ ] Golden step 1\n- [ ] VI router eval',
  'dependencies': 'V-3,V-4,V-7',
  'effort': 'M',
  'id': 'TC-09',
  'in_scope': 'VI log_expense route+extract.',
  'out_scope': 'Full UI i18n.',
  'phase': '0.5',
  'priority': 'Must',
  'proposal': 'Utterance bank + routes; hybrid ≥95%.',
  'refs': 'TC-09, V-1',
  'related': 'v-01-vietnamese-utterance-bank.md',
  'risks': 'Keyword CI gap',
  'slug': 'tc-09-vietnamese-expense-chat',
  'status': 'Planned',
  'summary': 'Chi tiêu … in Vietnamese.',
  'title': 'Vietnamese expense chat'},
 {'acceptance': '- [ ] VI income bank passes',
  'dependencies': 'V-1,V-3',
  'effort': 'M',
  'id': 'TC-10',
  'in_scope': 'log_income VI.',
  'out_scope': '—',
  'phase': '0.5',
  'priority': 'Must',
  'proposal': 'VI income routes + lương/thưởng hints.',
  'refs': 'TC-10',
  'related': 'tc-09-vietnamese-expense-chat.md',
  'risks': 'False expense routing',
  'slug': 'tc-10-vietnamese-income-chat',
  'status': 'Planned',
  'summary': 'Nhận lương … in Vietnamese.',
  'title': 'Vietnamese income chat'},
 {'acceptance': '- [ ] All Appendix B unit tests',
  'dependencies': '—',
  'effort': 'M',
  'id': 'TC-11',
  'in_scope': 'Appendix B patterns.',
  'out_scope': 'FX.',
  'phase': '0.5',
  'priority': 'Must',
  'proposal': 'Extend parse_amount + tests.',
  'refs': 'TC-11, V-3',
  'related': 'v-03-vnd-amount-parsing.md',
  'risks': 'triệu ambiguity',
  'slug': 'tc-11-vnd-amount-formats',
  'status': 'Planned',
  'summary': '50k, triệu, 500.000đ parsing.',
  'title': 'VND amount formats'},
 {'acceptance': 'TBD',
  'dependencies': 'MB-02',
  'effort': 'XL',
  'id': 'TC-12',
  'in_scope': 'N/A',
  'out_scope': '—',
  'phase': '—',
  'priority': 'Could',
  'proposal': 'Defer to mobile.',
  'refs': 'TC-12',
  'related': 'mb-02-native-mobile-app.md',
  'risks': 'OCR VI quality',
  'slug': 'tc-12-receipt-photo-capture',
  'status': 'Future',
  'summary': 'Photo → transaction.',
  'title': 'Receipt OCR'},
 {'acceptance': 'TBD',
  'dependencies': 'MB-02',
  'effort': 'L',
  'id': 'TC-13',
  'in_scope': 'N/A',
  'out_scope': '—',
  'phase': '—',
  'priority': 'Could',
  'proposal': 'Defer mobile-first.',
  'refs': 'TC-13',
  'related': 'mb-02-native-mobile-app.md',
  'risks': 'VI STT',
  'slug': 'tc-13-voice-input',
  'status': 'Future',
  'summary': 'Dictate transactions.',
  'title': 'Voice input'},
 {'acceptance': 'TBD',
  'dependencies': 'DS-06',
  'effort': 'L',
  'id': 'TC-14',
  'in_scope': 'N/A',
  'out_scope': 'Live bank feed',
  'phase': '—',
  'priority': 'Could',
  'proposal': 'After backup format; pending review.',
  'refs': 'TC-14',
  'related': 'ds-06-backup-restore.md',
  'risks': 'Dedup',
  'slug': 'tc-14-bulk-import-csv',
  'status': 'Future',
  'summary': 'Import bank CSV.',
  'title': 'Bulk CSV import'},
 {'acceptance': '- [x] Card shows pending fields',
  'dependencies': 'chat-payloads.json, TransactionCard',
  'effort': '—',
  'id': 'PM-01',
  'in_scope': 'Pending card in chat with all fields.',
  'out_scope': 'Auto-confirm without review.',
  'phase': 'MVP',
  'priority': 'Must',
  'proposal': 'Maintain transaction_pending payload and TransactionCard rendering.',
  'refs': 'PM-01',
  'related': 'pm-10-vietnamese-pending-actions.md',
  'risks': 'Low',
  'slug': 'pm-01-pending-card-review',
  'status': 'Shipped',
  'summary': 'See amount, category, and date on the pending card before save.',
  'title': 'Review pending card in chat'},
 {'acceptance': '- [x] Confirmed row persisted',
  'dependencies': 'DialogueEngine',
  'effort': '—',
  'id': 'PM-02',
  'in_scope': 'English confirm keywords and webhook handler.',
  'out_scope': 'Saving without explicit confirm.',
  'phase': 'MVP',
  'priority': 'Must',
  'proposal': 'Maintain manage_confirm; add Vietnamese phrases in Phase 0.5.',
  'refs': 'PM-02',
  'related': 'pm-10-vietnamese-pending-actions.md, v-02-vietnamese-pending-replies.md',
  'risks': 'Vietnamese blocked until 0.5',
  'slug': 'pm-02-confirm-via-chat',
  'status': 'Shipped',
  'summary': 'Say confirm or yes to save the pending transaction.',
  'title': 'Confirm pending via chat'},
 {'acceptance': '- [x] E2E confirm path',
  'dependencies': 'TransactionCard, Playwright E2E',
  'effort': '—',
  'id': 'PM-03',
  'in_scope': 'Confirm button on TransactionCard.',
  'out_scope': '—',
  'phase': 'MVP',
  'priority': 'Must',
  'proposal': 'Maintain structured confirm message to webhook.',
  'refs': 'PM-03',
  'related': 'pm-02-confirm-via-chat.md',
  'risks': '—',
  'slug': 'pm-03-confirm-via-ui',
  'status': 'Shipped',
  'summary': 'Click Confirm on the pending card to save.',
  'title': 'Confirm via UI button'},
 {'acceptance': '- [x] Pending cleared on discard',
  'dependencies': 'DialogueEngine',
  'effort': '—',
  'id': 'PM-04',
  'in_scope': 'English discard keywords.',
  'out_scope': '—',
  'phase': 'MVP',
  'priority': 'Must',
  'proposal': 'Maintain manage_discard; extend for Vietnamese.',
  'refs': 'PM-04',
  'related': 'pm-10-vietnamese-pending-actions.md',
  'risks': 'VI Phase 0.5',
  'slug': 'pm-04-discard-via-chat',
  'status': 'Shipped',
  'summary': 'Say discard or cancel to drop pending without saving.',
  'title': 'Discard pending via chat'},
 {'acceptance': '- [x] E2E discard',
  'dependencies': 'TransactionCard',
  'effort': '—',
  'id': 'PM-05',
  'in_scope': 'UI sends discard to backend.',
  'out_scope': '—',
  'phase': 'MVP',
  'priority': 'Must',
  'proposal': 'Keep E2E discard-transaction.spec.ts green.',
  'refs': 'PM-05',
  'related': 'pm-04-discard-via-chat.md',
  'risks': '—',
  'slug': 'pm-05-discard-via-ui',
  'status': 'Shipped',
  'summary': 'Click Discard on the card to cancel pending.',
  'title': 'Discard via UI button'},
 {'acceptance': '- [x] Webhook edit tests',
  'dependencies': 'Pending handler',
  'effort': '—',
  'id': 'PM-06',
  'in_scope': 'Amount edit on pending only.',
  'out_scope': 'Post-confirm amount edit.',
  'phase': 'MVP',
  'priority': 'Must',
  'proposal': 'Maintain edit rules; add Vietnamese (V-5).',
  'refs': 'PM-06',
  'related': 'v-05-vietnamese-edit-phrases.md',
  'risks': 'VI edit phrases',
  'slug': 'pm-06-edit-amount-chat',
  'status': 'Shipped',
  'summary': 'Change pending amount before confirm, e.g. change amount to 50.',
  'title': 'Edit amount via chat'},
 {'acceptance': '- [x] Phase 0 webhook tests',
  'dependencies': 'Pending handler, rules',
  'effort': '—',
  'id': 'PM-07',
  'in_scope': 'Category edit on pending.',
  'out_scope': '—',
  'phase': 'MVP',
  'priority': 'Must',
  'proposal': 'Maintain English hints; map Vietnamese categories (V-4).',
  'refs': 'PM-07',
  'related': 'v-04-vietnamese-category-hints.md',
  'risks': 'Category ambiguity',
  'slug': 'pm-07-edit-category-chat',
  'status': 'Shipped',
  'summary': 'Change pending category before confirm.',
  'title': 'Edit category via chat'},
 {'acceptance': '- [ ] VI-friendly edit from card',
  'dependencies': 'TransactionCard',
  'effort': 'M',
  'id': 'PM-08',
  'in_scope': 'Card edit mode exists.',
  'out_scope': 'Full post-confirm CRUD.',
  'phase': 'MVP',
  'priority': 'Should',
  'proposal': 'Improve inline edit UX and Vietnamese structured messages from UI.',
  'refs': 'PM-08',
  'related': 'pm-06-edit-amount-chat.md, pm-07-edit-category-chat.md',
  'risks': 'Confirm still English structured',
  'slug': 'pm-08-edit-via-card-ui',
  'status': 'Partial',
  'summary': 'Edit fields on the pending card before confirm.',
  'title': 'Edit via card UI (inline)'},
 {'acceptance': '- [ ] change date to yesterday',
  'dependencies': 'TC-06, TC-07',
  'effort': 'S',
  'id': 'PM-09',
  'in_scope': 'Description and limited date edit.',
  'out_scope': 'Complex natural-language dates.',
  'phase': 'MVP',
  'priority': 'Could',
  'proposal': 'Extend description and date edit rules; Vietnamese dates.',
  'refs': 'PM-09',
  'related': 'tc-06-transaction-description.md, tc-07-relative-dates-chat.md',
  'risks': 'Date edit limited today',
  'slug': 'pm-09-edit-description-date',
  'status': 'Partial',
  'summary': 'Edit memo or transaction date on pending via chat.',
  'title': 'Edit description/date via chat'},
 {'acceptance': '- [ ] Golden flow steps 2–3 in VI',
  'dependencies': 'v-02-vietnamese-pending-replies.md',
  'effort': 'M',
  'id': 'PM-10',
  'in_scope': 'VI short replies for pending lifecycle.',
  'out_scope': '—',
  'phase': '0.5',
  'priority': 'Must',
  'proposal': 'Implement V-2 pending regex and webhook tests in Vietnamese.',
  'refs': 'PM-10, V-2',
  'related': 'v-02-vietnamese-pending-replies.md, v-05-vietnamese-edit-phrases.md',
  'risks': 'Keyword CI may miss VI',
  'slug': 'pm-10-vietnamese-pending-actions',
  'status': 'Planned',
  'summary': 'Xác nhận, Hủy, Sửa thành 60k without English.',
  'title': 'Vietnamese confirm/discard/edit'},
 {'acceptance': '- [x] test_session_persist.py',
  'dependencies': 'eng-sqlite-sessions.md',
  'effort': '—',
  'id': 'PM-11',
  'in_scope': 'Session restore for pending flows.',
  'out_scope': 'Cross-device sync.',
  'phase': 'P2',
  'priority': 'Must',
  'proposal': 'Maintain SQLite chat_sessions persistence.',
  'refs': 'PM-11',
  'related': 'eng-sqlite-sessions.md, eq-02-session-survives-restart.md',
  'risks': '—',
  'slug': 'pm-11-pending-survives-restart',
  'status': 'Shipped',
  'summary': 'Pending and collecting state restored after backend restart.',
  'title': 'Pending survives backend restart'},
 {'acceptance': '- [ ] Documented + tested conflict',
  'dependencies': 'DialogueEngine',
  'effort': 'S',
  'id': 'PM-12',
  'in_scope': 'Explicit UX for pending conflict.',
  'out_scope': 'Multiple simultaneous pending cards.',
  'phase': 'MVP',
  'priority': 'Should',
  'proposal': 'Document and test replace-or-block policy.',
  'refs': 'PM-12',
  'related': 'pm-01-pending-card-review.md',
  'risks': 'Implicit behavior today',
  'slug': 'pm-12-single-pending-behavior',
  'status': 'Partial',
  'summary': 'Clear behavior when user starts a new expense while another is pending.',
  'title': 'One pending at a time'},
 {'acceptance': '- [x] Second confirm is no-op',
  'dependencies': 'services/transactions',
  'effort': '—',
  'id': 'PM-13',
  'in_scope': 'Idempotent confirm handler.',
  'out_scope': '—',
  'phase': 'MVP',
  'priority': 'Must',
  'proposal': 'Keep confirmed guard in update_transaction.',
  'refs': 'PM-13',
  'related': 'pm-02-confirm-via-chat.md',
  'risks': '—',
  'slug': 'pm-13-idempotent-confirm',
  'status': 'Shipped',
  'summary': 'Confirming twice must not create duplicate transactions.',
  'title': 'Idempotent confirm'},
 {'acceptance': '- [x] list_transactions works EN',
  'dependencies': 'DialogueEngine',
  'effort': '—',
  'id': 'CM-01',
  'in_scope': 'Chat list of confirmed rows.',
  'out_scope': 'Rich filters in chat.',
  'phase': 'MVP',
  'priority': 'Should',
  'proposal': 'Maintain list_transactions intent; add VI routing.',
  'refs': 'CM-01',
  'related': 'cm-02-list-period-filter-chat.md',
  'risks': 'VI Phase 0.5',
  'slug': 'cm-01-list-transactions-chat',
  'status': 'Shipped',
  'summary': 'Ask to show recent transactions in chat.',
  'title': 'List confirmed transactions (chat)'},
 {'acceptance': '- [x] EN periods',
  'dependencies': 'parse_period_from_text',
  'effort': 'S',
  'id': 'CM-02',
  'in_scope': 'English period patterns.',
  'out_scope': 'Custom date ranges.',
  'phase': 'MVP',
  'priority': 'Should',
  'proposal': 'Extend period parsing for Vietnamese.',
  'refs': 'CM-02',
  'related': 'rq-07-vietnamese-report-questions.md',
  'risks': 'VI periods missing',
  'slug': 'cm-02-list-period-filter-chat',
  'status': 'Partial',
  'summary': 'Filter list by last 7 days, this month, etc.',
  'title': 'List with period filter (chat)'},
 {'acceptance': '- [ ] grocery spending list',
  'dependencies': 'parse_category_hint',
  'effort': 'S',
  'id': 'CM-03',
  'in_scope': 'Category-scoped list in chat.',
  'out_scope': '—',
  'phase': 'MVP',
  'priority': 'Could',
  'proposal': 'English category hints only today.',
  'refs': 'CM-03',
  'related': 'v-04-vietnamese-category-hints.md',
  'risks': 'EN-only hints',
  'slug': 'cm-03-list-category-filter-chat',
  'status': 'Partial',
  'summary': 'Filter transactions by category in chat.',
  'title': 'List with category filter (chat)'},
 {'acceptance': '- [ ] List page with filters',
  'dependencies': 'Frontend routes',
  'effort': 'M',
  'id': 'CM-04',
  'in_scope': 'UI table of transactions.',
  'out_scope': 'Inline chat-only forever.',
  'phase': '1',
  'priority': 'Should',
  'proposal': 'Phase 1 F-3 read-only list with filters.',
  'refs': 'CM-04, F-3',
  'related': 'cm-05-edit-confirmed-ui.md',
  'risks': 'Scope creep vs chat',
  'slug': 'cm-04-transaction-list-ui',
  'status': 'Planned',
  'summary': 'Dedicated table or page for confirmed transactions.',
  'title': 'Transaction list in UI'},
 {'acceptance': '- [ ] Edit saves to SQLite',
  'dependencies': 'cm-04-transaction-list-ui.md',
  'effort': 'M',
  'id': 'CM-05',
  'in_scope': 'Edit single row in UI.',
  'out_scope': 'Bulk edit.',
  'phase': '1',
  'priority': 'Should',
  'proposal': 'Phase 1 F-4 manual CRUD form.',
  'refs': 'CM-05, F-4',
  'related': 'cm-04-transaction-list-ui.md',
  'risks': 'Auth later',
  'slug': 'cm-05-edit-confirmed-ui',
  'status': 'Planned',
  'summary': 'Fix mistakes after confirm via form.',
  'title': 'Edit confirmed transaction (UI)'},
 {'acceptance': 'TBD',
  'dependencies': '—',
  'effort': 'L',
  'id': 'CM-06',
  'in_scope': 'N/A until prioritized.',
  'out_scope': 'Pending edit confusion.',
  'phase': '—',
  'priority': 'Could',
  'proposal': 'Defer until intent + disambiguation designed.',
  'refs': 'CM-06',
  'related': 'cm-05-edit-confirmed-ui.md',
  'risks': 'Hard NLU problem',
  'slug': 'cm-06-edit-confirmed-chat',
  'status': 'Future',
  'summary': 'Change a saved transaction via natural language.',
  'title': 'Edit confirmed transaction (chat)'},
 {'acceptance': 'TBD',
  'dependencies': 'cm-04-transaction-list-ui.md',
  'effort': 'M',
  'id': 'CM-07',
  'in_scope': 'DELETE one transaction.',
  'out_scope': 'Soft-delete only.',
  'phase': '—',
  'priority': 'Should',
  'proposal': 'Consider Phase 1 alongside list UI.',
  'refs': 'CM-07',
  'related': 'cm-09-soft-delete-audit.md',
  'risks': 'Audit trail needs',
  'slug': 'cm-07-delete-single-confirmed',
  'status': 'Future',
  'summary': 'Remove one historical row without clearing all.',
  'title': 'Delete single confirmed transaction'},
 {'acceptance': '- [x] Clear txs works',
  'dependencies': 'API route',
  'effort': '—',
  'id': 'CM-08',
  'in_scope': 'Clear all txs control.',
  'out_scope': 'Selective delete (see CM-07).',
  'phase': 'MVP',
  'priority': 'Could',
  'proposal': 'Maintain DELETE /data/transactions.',
  'refs': 'CM-08',
  'related': 'cm-07-delete-single-confirmed.md',
  'risks': 'Destructive UX',
  'slug': 'cm-08-delete-all-transactions',
  'status': 'Shipped',
  'summary': 'Reset all transaction data from header.',
  'title': 'Delete all transactions'},
 {'acceptance': '- [x] discarded in DB',
  'dependencies': 'SQLite schema',
  'effort': 'S',
  'id': 'CM-09',
  'in_scope': 'DB status for discarded.',
  'out_scope': 'Full audit UI.',
  'phase': 'MVP',
  'priority': 'Could',
  'proposal': 'discarded status exists; expose audit API later if needed.',
  'refs': 'CM-09',
  'related': 'cm-07-delete-single-confirmed.md',
  'risks': 'Hidden from list API',
  'slug': 'cm-09-soft-delete-audit',
  'status': 'Partial',
  'summary': 'Discarded and deleted rows tracked but hidden from default API.',
  'title': 'Soft-delete / audit trail'},
 {'acceptance': '- [x] test_webhook_reports balance',
  'dependencies': 'get_balance.py',
  'effort': '—',
  'id': 'RQ-01',
  'in_scope': 'Template SQL balance report.',
  'out_scope': 'LLM prose reports.',
  'phase': 'MVP',
  'priority': 'Must',
  'proposal': 'Maintain check_balance and balance payload.',
  'refs': 'RQ-01',
  'related': 'rq-07-vietnamese-report-questions.md',
  'risks': 'VI Phase 0.5',
  'slug': 'rq-01-balance-net-chat',
  'status': 'Shipped',
  'summary': "What's my balance this month via chat.",
  'title': 'Balance / net (income − expenses)'},
 {'acceptance': '- [x] spending report tests',
  'dependencies': 'query_spending.py',
  'effort': '—',
  'id': 'RQ-02',
  'in_scope': 'Period spending total.',
  'out_scope': '—',
  'phase': 'MVP',
  'priority': 'Must',
  'proposal': 'Maintain analyze_spending intent.',
  'refs': 'RQ-02',
  'related': 'rq-05-period-this-last-month.md',
  'risks': 'EN periods',
  'slug': 'rq-02-spending-total-period',
  'status': 'Shipped',
  'summary': 'How much did I spend last month.',
  'title': 'Spending total by period'},
 {'acceptance': '- [x] category rows in report',
  'dependencies': 'SQL templates',
  'effort': '—',
  'id': 'RQ-03',
  'in_scope': 'Category breakdown in template.',
  'out_scope': 'LLM narrative.',
  'phase': 'MVP',
  'priority': 'Must',
  'proposal': 'Maintain spending_report payload.',
  'refs': 'RQ-03',
  'related': 'db-08-vietnamese-category-labels.md',
  'risks': 'VI labels later',
  'slug': 'rq-03-spending-by-category',
  'status': 'Shipped',
  'summary': 'Category breakdown in spending report card.',
  'title': 'Spending by category'},
 {'acceptance': '- [ ] EN category filter',
  'dependencies': 'rules + SQL',
  'effort': 'S',
  'id': 'RQ-04',
  'in_scope': 'Filtered spending query.',
  'out_scope': '—',
  'phase': 'MVP',
  'priority': 'Should',
  'proposal': 'English parse_category_hint only.',
  'refs': 'RQ-04',
  'related': 'v-04-vietnamese-category-hints.md',
  'risks': 'VI hints Phase 0.5',
  'slug': 'rq-04-category-scoped-spending',
  'status': 'Partial',
  'summary': 'Show my grocery spending for a period.',
  'title': 'Category-scoped spending query'},
 {'acceptance': '- [x] EN month windows',
  'dependencies': 'utils/dates',
  'effort': '—',
  'id': 'RQ-05',
  'in_scope': 'this month, last month.',
  'out_scope': 'Custom ranges.',
  'phase': 'MVP',
  'priority': 'Must',
  'proposal': 'Maintain parse_period_from_text.',
  'refs': 'RQ-05',
  'related': 'st-03-timezone-setting.md',
  'risks': 'TZ edge cases',
  'slug': 'rq-05-period-this-last-month',
  'status': 'Shipped',
  'summary': 'Default reporting windows for this/last month.',
  'title': 'Period: this month / last month'},
 {'acceptance': '- [x] EN 7d/30d partial',
  'dependencies': 'parse_period_from_text',
  'effort': 'S',
  'id': 'RQ-06',
  'in_scope': 'Extended period tokens EN.',
  'out_scope': 'Arbitrary ranges.',
  'phase': 'MVP',
  'priority': 'Should',
  'proposal': 'English regex only; add VI.',
  'refs': 'RQ-06',
  'related': 'rq-07-vietnamese-report-questions.md',
  'risks': 'VI missing',
  'slug': 'rq-06-period-extended-windows',
  'status': 'Partial',
  'summary': 'Extended windows like last 7 days and YTD.',
  'title': 'Period: 7d / 30d / 3m / YTD'},
 {'acceptance': '- [ ] Golden steps 4–5 VI',
  'dependencies': 'V-1, V-8',
  'effort': 'M',
  'id': 'RQ-07',
  'in_scope': 'VI balance and spending intents.',
  'out_scope': 'LLM report prose.',
  'phase': '0.5',
  'priority': 'Must',
  'proposal': 'VI routes + templates (V-1, V-8).',
  'refs': 'RQ-07, V-1, V-8',
  'related': 'v-01-vietnamese-utterance-bank.md, v-08-vietnamese-bot-templates.md',
  'risks': 'Router eval for VI',
  'slug': 'rq-07-vietnamese-report-questions',
  'status': 'Planned',
  'summary': 'Tháng nay chi bao nhiêu, Số dư tháng này.',
  'title': 'Vietnamese report questions'},
 {'acceptance': '- [ ] Trend message in VI',
  'dependencies': 'SQL + templates',
  'effort': 'M',
  'id': 'RQ-08',
  'in_scope': 'Period-over-period delta in chat.',
  'out_scope': 'Open-ended NL analytics.',
  'phase': '1',
  'priority': 'Should',
  'proposal': 'Phase 1 F-1 trend comparison templates.',
  'refs': 'RQ-08, F-1',
  'related': 'rq-02-spending-total-period.md',
  'risks': 'Query complexity',
  'slug': 'rq-08-trend-vs-prior-period',
  'status': 'Planned',
  'summary': '12% more on dining vs last month.',
  'title': 'Trend vs prior period'},
 {'acceptance': '- [x] Dashboard tabs',
  'dependencies': 'DashboardPanel',
  'effort': 'S',
  'id': 'RQ-09',
  'in_scope': 'Dashboard tab breakdown.',
  'out_scope': 'Full chat tab parity.',
  'phase': 'MVP',
  'priority': 'Could',
  'proposal': 'Dashboard tabs exist; align chat templates if needed.',
  'refs': 'RQ-09',
  'related': 'db-03-dashboard-tabs.md',
  'risks': 'Chat combined today',
  'slug': 'rq-09-income-expense-summary-tabs',
  'status': 'Partial',
  'summary': 'Separate income vs expense views.',
  'title': 'Income-only or expense-only summary'},
 {'acceptance': 'TBD',
  'dependencies': 'parse_period',
  'effort': 'M',
  'id': 'RQ-10',
  'in_scope': 'N/A',
  'out_scope': '—',
  'phase': '—',
  'priority': 'Could',
  'proposal': 'Defer until period parser supports ranges.',
  'refs': 'RQ-10',
  'related': 'db-06-dashboard-date-range.md',
  'risks': 'NL date complexity',
  'slug': 'rq-10-custom-date-range-chat',
  'status': 'Future',
  'summary': 'From Jan 1 to Jan 15 in natural language.',
  'title': 'Custom date range in chat'},
 {'acceptance': 'N/A',
  'dependencies': '—',
  'effort': '—',
  'id': 'RQ-11',
  'in_scope': 'N/A',
  'out_scope': '—',
  'phase': '—',
  'priority': "Won't",
  'proposal': 'Reject; templates + SQL only per ADR.',
  'refs': 'RQ-11',
  'related': 'oos-llm-report-prose.md',
  'risks': 'ADR violation',
  'slug': 'rq-11-llm-narrative-report',
  'status': 'Out of scope',
  'summary': 'Prose summary of finances via LLM.',
  'title': 'LLM-generated narrative report'},
 {'acceptance': 'TBD when slow',
  'dependencies': 'eng-duckdb-analytics.md',
  'effort': 'L',
  'id': 'RQ-12',
  'in_scope': 'Read-only analytics path.',
  'out_scope': 'DuckDB in unrelated PRs.',
  'phase': '5',
  'priority': "Won't (now)",
  'proposal': 'Trigger DuckDB (eng-duckdb-analytics) when profiling shows pain.',
  'refs': 'RQ-12, P4',
  'related': 'eng-duckdb-analytics.md',
  'risks': 'Scope creep',
  'slug': 'rq-12-fast-analytics-scale',
  'status': 'Roadmap',
  'summary': 'Large history aggregations without slow SQLite.',
  'title': 'Fast analytics at scale'},
 {'acceptance': '- [x] Overview renders',
  'dependencies': 'finance-calculations',
  'effort': '—',
  'id': 'DB-01',
  'in_scope': 'Net, income, expense for month.',
  'out_scope': 'Multi-month without picker.',
  'phase': 'MVP',
  'priority': 'Must',
  'proposal': 'Maintain DashboardPanel calculations.',
  'refs': 'DB-01',
  'related': 'db-06-dashboard-date-range.md',
  'risks': 'EN labels',
  'slug': 'db-01-monthly-overview',
  'status': 'Shipped',
  'summary': 'Glance at current month totals in sidebar.',
  'title': 'Monthly overview (net, income, expenses)'},
 {'acceptance': '- [x] Chart renders',
  'dependencies': 'DashboardPanel',
  'effort': '—',
  'id': 'DB-02',
  'in_scope': 'Category bar chart.',
  'out_scope': '—',
  'phase': 'MVP',
  'priority': 'Must',
  'proposal': 'Maintain category chart; VI labels Phase 1.',
  'refs': 'DB-02',
  'related': 'db-08-vietnamese-category-labels.md',
  'risks': 'Slug labels EN',
  'slug': 'db-02-category-breakdown-chart',
  'status': 'Shipped',
  'summary': 'See where money goes via SVG bars.',
  'title': 'Category breakdown chart'},
 {'acceptance': '- [x] Tabs switch',
  'dependencies': 'Frontend',
  'effort': '—',
  'id': 'DB-03',
  'in_scope': 'Three tab views.',
  'out_scope': '—',
  'phase': 'MVP',
  'priority': 'Should',
  'proposal': 'Maintain tab UI.',
  'refs': 'DB-03',
  'related': 'rq-09-income-expense-summary-tabs.md',
  'risks': '—',
  'slug': 'db-03-dashboard-tabs',
  'status': 'Shipped',
  'summary': 'Switch dashboard views by tab.',
  'title': 'Income / expense / overview tabs'},
 {'acceptance': '- [x] Toggle works',
  'dependencies': 'ChatWorkspace',
  'effort': '—',
  'id': 'DB-04',
  'in_scope': 'Header show/hide.',
  'out_scope': '—',
  'phase': 'MVP',
  'priority': 'Could',
  'proposal': 'Maintain toggle control.',
  'refs': 'DB-04',
  'related': '—',
  'risks': '—',
  'slug': 'db-04-toggle-dashboard',
  'status': 'Shipped',
  'summary': 'Show or hide overview from header.',
  'title': 'Toggle dashboard visibility'},
 {'acceptance': '- [ ] Month boundary test TZ',
  'dependencies': 'st-03-timezone-setting.md',
  'effort': 'S',
  'id': 'DB-05',
  'in_scope': 'Backend TZ used; client month may drift.',
  'out_scope': '—',
  'phase': 'MVP',
  'priority': 'Should',
  'proposal': 'Align client month with profile timezone (ST-03).',
  'refs': 'DB-05',
  'related': 'st-03-timezone-setting.md',
  'risks': 'Client vs server month',
  'slug': 'db-05-dashboard-timezone',
  'status': 'Partial',
  'summary': 'Month boundaries match user timezone.',
  'title': 'Dashboard respects timezone'},
 {'acceptance': '- [ ] Custom range updates chart',
  'dependencies': 'Frontend',
  'effort': 'M',
  'id': 'DB-06',
  'in_scope': 'Date range on dashboard.',
  'out_scope': '—',
  'phase': '1',
  'priority': 'Should',
  'proposal': 'Phase 1 F-2 week/month/custom picker.',
  'refs': 'DB-06, F-2',
  'related': 'db-01-monthly-overview.md',
  'risks': '—',
  'slug': 'db-06-dashboard-date-range',
  'status': 'Planned',
  'summary': 'Not only current calendar month.',
  'title': 'Dashboard date range picker'},
 {'acceptance': '- [ ] VND displays correctly',
  'dependencies': 'st-02-currency-setting.md',
  'effort': 'S',
  'id': 'DB-07',
  'in_scope': 'Currency from profile in UI.',
  'out_scope': 'Multi-currency per tx.',
  'phase': 'MVP',
  'priority': 'Must',
  'proposal': 'Fix UI formatter to read profile currency.',
  'refs': 'DB-07',
  'related': 'st-02-currency-setting.md, v-06-vnd-default-profile.md',
  'risks': 'USD hardcoded today',
  'slug': 'db-07-profile-currency-charts',
  'status': 'Partial',
  'summary': 'formatMoney uses profile currency not hardcoded USD.',
  'title': 'VND / profile currency in charts'},
 {'acceptance': '- [ ] Labels in dashboard',
  'dependencies': 'F-5',
  'effort': 'S',
  'id': 'DB-08',
  'in_scope': 'VI display labels.',
  'out_scope': 'Custom taxonomy editor.',
  'phase': '1',
  'priority': 'Should',
  'proposal': 'Phase 1 F-5 slug→label map.',
  'refs': 'DB-08, F-5',
  'related': 'v-04-vietnamese-category-hints.md',
  'risks': '—',
  'slug': 'db-08-vietnamese-category-labels',
  'status': 'Planned',
  'summary': 'Ăn uống instead of dining slug in UI.',
  'title': 'Vietnamese category labels'},
 {'acceptance': 'TBD',
  'dependencies': 'bg-03-budget-bars-dashboard.md',
  'effort': 'L',
  'id': 'DB-09',
  'in_scope': 'Budget bars on dashboard.',
  'out_scope': '—',
  'phase': '2',
  'priority': 'Should',
  'proposal': 'Phase 2 B-3 after budgets data model.',
  'refs': 'DB-09, B-3',
  'related': 'bg-03-budget-bars-dashboard.md, eng-burr-fsm.md',
  'risks': '7th flow → Burr',
  'slug': 'db-09-budget-progress-bars',
  'status': 'Planned',
  'summary': 'Visual category vs budget limit.',
  'title': 'Budget progress bars'},
 {'acceptance': 'TBD',
  'dependencies': '—',
  'effort': 'M',
  'id': 'DB-10',
  'in_scope': 'N/A',
  'out_scope': '—',
  'phase': '—',
  'priority': 'Could',
  'proposal': 'Defer.',
  'refs': 'DB-10',
  'related': 'ds-04-export-csv.md',
  'risks': '—',
  'slug': 'db-10-export-chart-share',
  'status': 'Future',
  'summary': 'PDF or image export of dashboard.',
  'title': 'Export chart / share report'},
 {'acceptance': '- [x] E2E settings',
  'dependencies': 'Settings API',
  'effort': '—',
  'id': 'ST-01',
  'in_scope': 'Name field.',
  'out_scope': '—',
  'phase': 'MVP',
  'priority': 'Could',
  'proposal': 'Maintain Settings PATCH profile.',
  'refs': 'ST-01',
  'related': '—',
  'risks': '—',
  'slug': 'st-01-display-name',
  'status': 'Shipped',
  'summary': 'Personalize profile display name.',
  'title': 'Set display name'},
 {'acceptance': '- [x] VND in list',
  'dependencies': 'schema profile',
  'effort': '—',
  'id': 'ST-02',
  'in_scope': 'Profile currency.',
  'out_scope': 'Per-tx currency.',
  'phase': 'MVP',
  'priority': 'Must',
  'proposal': 'Maintain currency list; default VND in 0.5 (V-6).',
  'refs': 'ST-02',
  'related': 'v-06-vnd-default-profile.md, db-07-profile-currency-charts.md',
  'risks': 'Default still USD',
  'slug': 'st-02-currency-setting',
  'status': 'Shipped',
  'summary': 'Choose VND, USD, etc.',
  'title': 'Set currency'},
 {'acceptance': '- [x] E2E timezone',
  'dependencies': 'PATCH profile',
  'effort': '—',
  'id': 'ST-03',
  'in_scope': 'Timezone field.',
  'out_scope': '—',
  'phase': 'MVP',
  'priority': 'Must',
  'proposal': 'Maintain timezone on profile for reports.',
  'refs': 'ST-03',
  'related': 'db-05-dashboard-timezone.md',
  'risks': 'Dashboard client TZ',
  'slug': 'st-03-timezone-setting',
  'status': 'Shipped',
  'summary': 'Asia/Ho_Chi_Minh and other TZs.',
  'title': 'Set timezone'},
 {'acceptance': '- [ ] New local user gets VND+TZ',
  'dependencies': 'v-06-vnd-default-profile.md',
  'effort': 'S',
  'id': 'ST-04',
  'in_scope': 'Local user defaults.',
  'out_scope': '—',
  'phase': '0.5',
  'priority': 'Must',
  'proposal': 'Seed VND and Asia/Ho_Chi_Minh in schema bootstrap.',
  'refs': 'ST-04, V-6',
  'related': 'v-06-vnd-default-profile.md',
  'risks': '—',
  'slug': 'st-04-vnd-hcm-defaults',
  'status': 'Planned',
  'summary': 'Sensible defaults for local Vietnamese user.',
  'title': 'Default VND + Ho Chi Minh'},
 {'acceptance': '- [ ] locale=vi selects VI templates',
  'dependencies': 'v-10-locale-on-profile.md',
  'effort': 'M',
  'id': 'ST-05',
  'in_scope': 'locale on profile.',
  'out_scope': 'Full i18n framework.',
  'phase': '0.5',
  'priority': 'Must',
  'proposal': 'V-10 locale field drives templates.',
  'refs': 'ST-05, V-10',
  'related': 'v-10-locale-on-profile.md, l-07-vietnamese-ui.md',
  'risks': 'Big-bang i18n',
  'slug': 'st-05-language-locale-preference',
  'status': 'Planned',
  'summary': 'UI and bot in Vietnamese when locale=vi.',
  'title': 'Language / locale preference'},
 {'acceptance': '- [ ] Toggle persists preference',
  'dependencies': 'TC-08',
  'effort': 'S',
  'id': 'ST-06',
  'in_scope': 'UI toggle for LLM_EXTRACT.',
  'out_scope': 'Per-message override.',
  'phase': 'MVP',
  'priority': 'Could',
  'proposal': 'Add Settings toggle wired to backend flag.',
  'refs': 'ST-06',
  'related': 'tc-08-llm-extract-fallback.md',
  'risks': 'Env-only today',
  'slug': 'st-06-llm-extract-toggle-ui',
  'status': 'Partial',
  'summary': 'User controls LLM extract without env vars.',
  'title': 'Enable/disable LLM extraction (UI)'},
 {'acceptance': 'TBD',
  'dependencies': 'MB-03',
  'effort': 'L',
  'id': 'ST-07',
  'in_scope': 'N/A',
  'out_scope': '—',
  'phase': '—',
  'priority': 'Could',
  'proposal': 'Defer until notification channel exists.',
  'refs': 'ST-07',
  'related': 'mb-03-push-budget-alert.md',
  'risks': '—',
  'slug': 'st-07-notification-preferences',
  'status': 'Future',
  'summary': 'Alerts and reminders settings.',
  'title': 'Notification preferences'},
 {'acceptance': 'TBD',
  'dependencies': '—',
  'effort': 'L',
  'id': 'ST-08',
  'in_scope': 'N/A',
  'out_scope': '—',
  'phase': '—',
  'priority': 'Should',
  'proposal': 'Defer; fixed slugs in UI types today.',
  'refs': 'ST-08',
  'related': 'db-08-vietnamese-category-labels.md',
  'risks': 'Migration from slugs',
  'slug': 'st-08-custom-category-taxonomy',
  'status': 'Future',
  'summary': 'User-defined category list.',
  'title': 'Custom category taxonomy'},
 {'acceptance': '- [x] DB file exists',
  'dependencies': 'backend/data',
  'effort': '—',
  'id': 'DS-01',
  'in_scope': 'Local SQLite file.',
  'out_scope': 'Postgres (Phase 4).',
  'phase': 'MVP',
  'priority': 'Must',
  'proposal': 'Maintain SQLite OLTP.',
  'refs': 'DS-01',
  'related': 'au-04-postgres-migration.md',
  'risks': 'Single-user',
  'slug': 'ds-01-sqlite-persist',
  'status': 'Shipped',
  'summary': 'SQLite finguard.db on disk.',
  'title': 'Persist transactions locally'},
 {'acceptance': '- [x] Refresh keeps messages',
  'dependencies': 'frontend storage',
  'effort': '—',
  'id': 'DS-02',
  'in_scope': 'Browser chat history.',
  'out_scope': 'Server-side chat log.',
  'phase': 'MVP',
  'priority': 'Should',
  'proposal': 'Maintain chat-storage.',
  'refs': 'DS-02',
  'related': 'ds-05-clear-chat-only.md',
  'risks': '—',
  'slug': 'ds-02-chat-history-browser',
  'status': 'Shipped',
  'summary': 'Reload chat on refresh via localStorage.',
  'title': 'Persist chat history in browser'},
 {'acceptance': '- [x] CP-4 partial',
  'dependencies': 'API client',
  'effort': '—',
  'id': 'DS-03',
  'in_scope': 'Fetch txs on load.',
  'out_scope': '—',
  'phase': 'MVP',
  'priority': 'Must',
  'proposal': 'Maintain hydrate on startup.',
  'refs': 'DS-03',
  'related': 'cm-04-transaction-list-ui.md',
  'risks': '—',
  'slug': 'ds-03-hydrate-on-load',
  'status': 'Shipped',
  'summary': 'Sidebar and chat sync transactions on app load.',
  'title': 'Hydrate transactions on load'},
 {'acceptance': '- [x] E2E export',
  'dependencies': 'export route',
  'effort': '—',
  'id': 'DS-04',
  'in_scope': 'CSV export endpoint.',
  'out_scope': 'Encrypted export.',
  'phase': 'MVP',
  'priority': 'Should',
  'proposal': 'Maintain /api/transactions/export E2E.',
  'refs': 'DS-04',
  'related': 'ds-06-backup-restore.md',
  'risks': '—',
  'slug': 'ds-04-export-csv',
  'status': 'Shipped',
  'summary': 'Download CSV for Excel.',
  'title': 'Export transactions CSV'},
 {'acceptance': '- [x] Clear chat works',
  'dependencies': 'chat-storage',
  'effort': '—',
  'id': 'DS-05',
  'in_scope': 'Chat-only clear.',
  'out_scope': '—',
  'phase': 'MVP',
  'priority': 'Could',
  'proposal': 'Maintain header Clear chat.',
  'refs': 'DS-05',
  'related': 'ds-02-chat-history-browser.md',
  'risks': '—',
  'slug': 'ds-05-clear-chat-only',
  'status': 'Shipped',
  'summary': 'Clear chat without deleting transactions.',
  'title': 'Clear chat history only'},
 {'acceptance': '- [ ] Round-trip restore',
  'dependencies': '—',
  'effort': 'S',
  'id': 'DS-06',
  'in_scope': 'Backup zip format.',
  'out_scope': 'Cloud sync.',
  'phase': '1',
  'priority': 'Should',
  'proposal': 'Phase 1 F-6 export/import bundle.',
  'refs': 'DS-06, F-6',
  'related': 'tc-14-bulk-import-csv.md',
  'risks': 'Format versioning',
  'slug': 'ds-06-backup-restore',
  'status': 'Planned',
  'summary': 'Move data to new device.',
  'title': 'Backup / restore full database'},
 {'acceptance': 'TBD',
  'dependencies': 'au-01-login-signup.md',
  'effort': 'XL',
  'id': 'DS-07',
  'in_scope': 'Multi-device sync.',
  'out_scope': 'Offline-first conflict',
  'phase': '4',
  'priority': 'Should',
  'proposal': 'Phase 4 auth + Postgres.',
  'refs': 'DS-07',
  'related': 'au-04-postgres-migration.md',
  'risks': 'Hosted scope',
  'slug': 'ds-07-cloud-sync',
  'status': 'Planned',
  'summary': 'Same data on phone and laptop.',
  'title': 'Cloud sync across devices'},
 {'acceptance': 'TBD',
  'dependencies': 'ds-06-backup-restore.md',
  'effort': 'M',
  'id': 'DS-08',
  'in_scope': 'N/A',
  'out_scope': '—',
  'phase': '—',
  'priority': 'Could',
  'proposal': 'Defer after F-6 plain backup.',
  'refs': 'DS-08',
  'related': 'ds-06-backup-restore.md',
  'risks': 'Key management',
  'slug': 'ds-08-encrypted-backup',
  'status': 'Future',
  'summary': 'Password-protected export.',
  'title': 'Encrypted backup'},
 {'acceptance': 'TBD',
  'dependencies': 'au-02-multi-user-isolation.md',
  'effort': 'L',
  'id': 'DS-09',
  'in_scope': 'Account deletion API.',
  'out_scope': '—',
  'phase': '4',
  'priority': 'Future',
  'proposal': 'Part of Phase 4 multi-user.',
  'refs': 'DS-09',
  'related': 'au-02-multi-user-isolation.md',
  'risks': '—',
  'slug': 'ds-09-gdpr-delete-account',
  'status': 'Future',
  'summary': 'Erase all user data on hosted deploy.',
  'title': 'GDPR-style delete account'},
 {'acceptance': '- [x] Welcome shows',
  'dependencies': 'ChatWorkspace',
  'effort': '—',
  'id': 'UX-01',
  'in_scope': 'English welcome + placeholders.',
  'out_scope': '—',
  'phase': 'MVP',
  'priority': 'Must',
  'proposal': 'Maintain English welcome until V-9 ships.',
  'refs': 'UX-01',
  'related': 'ux-02-welcome-vietnamese.md',
  'risks': '—',
  'slug': 'ux-01-welcome-english',
  'status': 'Shipped',
  'summary': 'Onboarding examples in chat on first load.',
  'title': 'Welcome message + examples (English)'},
 {'acceptance': '- [ ] VI welcome on vi locale',
  'dependencies': 'v-09-vietnamese-welcome-examples.md',
  'effort': 'S',
  'id': 'UX-02',
  'in_scope': 'VI welcome when locale=vi.',
  'out_scope': 'Full UI i18n.',
  'phase': '0.5',
  'priority': 'Must',
  'proposal': 'V-9 welcome and input placeholder copy.',
  'refs': 'UX-02, V-9',
  'related': 'v-09-vietnamese-welcome-examples.md',
  'risks': '—',
  'slug': 'ux-02-welcome-vietnamese',
  'status': 'Planned',
  'summary': 'Localized onboarding for Vietnamese users.',
  'title': 'Vietnamese welcome + examples'},
 {'acceptance': '- [x] Shows during fetch',
  'dependencies': 'Frontend',
  'effort': '—',
  'id': 'UX-03',
  'in_scope': 'Typing animation.',
  'out_scope': '—',
  'phase': 'MVP',
  'priority': 'Could',
  'proposal': 'Maintain TypingIndicator component.',
  'refs': 'UX-03',
  'related': '—',
  'risks': '—',
  'slug': 'ux-03-typing-indicator',
  'status': 'Shipped',
  'summary': 'Feedback while waiting for backend.',
  'title': 'Typing indicator'},
 {'acceptance': '- [x] E2E error path partial',
  'dependencies': 'Chat API',
  'effort': 'S',
  'id': 'UX-04',
  'in_scope': 'Error bubble + retry.',
  'out_scope': '—',
  'phase': 'MVP',
  'priority': 'Should',
  'proposal': 'Improve VI error copy; E2E error-rasa-down.',
  'refs': 'UX-04',
  'related': 'v-08-vietnamese-bot-templates.md',
  'risks': 'VI errors',
  'slug': 'ux-04-error-retry',
  'status': 'Partial',
  'summary': 'Backend down or timeout shows retry.',
  'title': 'Error message + retry'},
 {'acceptance': '- [x] 429 returned',
  'dependencies': 'middleware',
  'effort': '—',
  'id': 'UX-05',
  'in_scope': '429 handling.',
  'out_scope': 'Distributed limit (AU-08).',
  'phase': 'MVP',
  'priority': 'Should',
  'proposal': 'Maintain /api/chat rate limit response.',
  'refs': 'UX-05',
  'related': 'au-08-distributed-rate-limiting.md',
  'risks': 'Single-node limit',
  'slug': 'ux-05-rate-limit-message',
  'status': 'Shipped',
  'summary': '429 returns user-friendly message.',
  'title': 'Rate limit friendly message'},
 {'acceptance': '- [ ] help in VI',
  'dependencies': 'router',
  'effort': 'S',
  'id': 'UX-06',
  'in_scope': 'help intent text.',
  'out_scope': 'Open-ended chatbot.',
  'phase': 'MVP',
  'priority': 'Could',
  'proposal': 'English help only; VI templates later.',
  'refs': 'UX-06',
  'related': 'v-08-vietnamese-bot-templates.md',
  'risks': 'Low priority',
  'slug': 'ux-06-chitchat-help',
  'status': 'Partial',
  'summary': 'hello and help intents with guidance.',
  'title': 'Chitchat / help'},
 {'acceptance': '- [x] EN fallback',
  'dependencies': 'DialogueEngine',
  'effort': '—',
  'id': 'UX-07',
  'in_scope': 'Unknown intent message.',
  'out_scope': '—',
  'phase': 'MVP',
  'priority': 'Should',
  'proposal': 'English fallback; VI in V-8.',
  'refs': 'UX-07',
  'related': 'v-08-vietnamese-bot-templates.md',
  'risks': 'VI missing',
  'slug': 'ux-07-unknown-intent-guidance',
  'status': 'Shipped',
  'summary': 'Clarify what the app can do on unknown input.',
  'title': 'Unknown intent guidance'},
 {'acceptance': '- [x] Renders markdown',
  'dependencies': 'markdown.tsx',
  'effort': '—',
  'id': 'UX-08',
  'in_scope': 'Markdown subset in chat.',
  'out_scope': 'Unsafe HTML.',
  'phase': 'MVP',
  'priority': 'Could',
  'proposal': 'Maintain markdown.tsx rendering.',
  'refs': 'UX-08',
  'related': 'ux-09-safe-markdown.md',
  'risks': '—',
  'slug': 'ux-08-markdown-messages',
  'status': 'Shipped',
  'summary': 'Bold and lists in bot replies.',
  'title': 'Markdown in messages'},
 {'acceptance': '- [x] a11y-smoke',
  'dependencies': 'markdown.tsx',
  'effort': '—',
  'id': 'UX-09',
  'in_scope': 'XSS-safe rendering.',
  'out_scope': 'Raw HTML from user.',
  'phase': 'MVP',
  'priority': 'Must',
  'proposal': 'Maintain escape rules; a11y tests.',
  'refs': 'UX-09',
  'related': 'ux-08-markdown-messages.md',
  'risks': '—',
  'slug': 'ux-09-safe-markdown',
  'status': 'Shipped',
  'summary': 'HTML escaped in rendered messages.',
  'title': 'Safe markdown (no XSS)'},
 {'acceptance': '- [x] a11y-smoke exists',
  'dependencies': 'Playwright',
  'effort': 'S',
  'id': 'UX-10',
  'in_scope': 'Smoke a11y tests.',
  'out_scope': 'Full WCAG audit.',
  'phase': 'MVP',
  'priority': 'Should',
  'proposal': 'Expand a11y-smoke.spec.ts coverage.',
  'refs': 'UX-10',
  'related': '—',
  'risks': 'Gaps remain',
  'slug': 'ux-10-accessibility-smoke',
  'status': 'Partial',
  'summary': 'Basic a11y checks in Playwright.',
  'title': 'Accessibility smoke'},
 {'acceptance': '- [ ] ≥95% VI subset',
  'dependencies': 'v-01-vietnamese-utterance-bank.md',
  'effort': 'M',
  'id': 'L-01',
  'in_scope': 'VI routes in router.',
  'out_scope': 'LLM every turn.',
  'phase': '0.5',
  'priority': 'Must',
  'proposal': 'V-1 bank + V-7 hybrid eval gate.',
  'refs': 'L-01, V-1, V-7',
  'related': 'v-01-vietnamese-utterance-bank.md, v-07-hybrid-router-vi-eval.md',
  'risks': 'CI keyword gap',
  'slug': 'l-01-vietnamese-intent-routing',
  'status': 'Planned',
  'summary': 'Route Vietnamese utterances to correct intents.',
  'title': 'Vietnamese intent routing'},
 {'acceptance': '- [ ] V-2 tests pass',
  'dependencies': 'v-02-vietnamese-pending-replies.md',
  'effort': 'M',
  'id': 'L-02',
  'in_scope': 'VI confirm/discard/edit.',
  'out_scope': '—',
  'phase': '0.5',
  'priority': 'Must',
  'proposal': 'Same as V-2; linked for catalog L-02.',
  'refs': 'L-02, V-2',
  'related': 'v-02-vietnamese-pending-replies.md, pm-10-vietnamese-pending-actions.md',
  'risks': '—',
  'slug': 'l-02-vietnamese-pending-replies',
  'status': 'Planned',
  'summary': 'Short VI replies for pending lifecycle.',
  'title': 'Vietnamese pending replies'},
 {'acceptance': '- [ ] All pattern unit tests',
  'dependencies': 'v-03-vnd-amount-parsing.md',
  'effort': 'M',
  'id': 'L-03',
  'in_scope': 'Appendix B patterns.',
  'out_scope': 'FX',
  'phase': '0.5',
  'priority': 'Must',
  'proposal': 'Extend parse_amount (V-3).',
  'refs': 'L-03, V-3',
  'related': 'v-03-vnd-amount-parsing.md, tc-11-vnd-amount-formats.md',
  'risks': 'triệu ambiguity',
  'slug': 'l-03-vietnamese-amount-parsing',
  'status': 'Planned',
  'summary': 'Parse k, triệu, đ amounts.',
  'title': 'Vietnamese amount parsing'},
 {'acceptance': '- [ ] Hint tests',
  'dependencies': 'v-04-vietnamese-category-hints.md',
  'effort': 'M',
  'id': 'L-04',
  'in_scope': 'VI→slug map.',
  'out_scope': 'Custom categories',
  'phase': '0.5',
  'priority': 'Must',
  'proposal': 'Category hint table in rules.',
  'refs': 'L-04, V-4',
  'related': 'v-04-vietnamese-category-hints.md',
  'risks': '—',
  'slug': 'l-04-vietnamese-category-mapping',
  'status': 'Planned',
  'summary': 'Map ăn uống, đi lại to slugs.',
  'title': 'Vietnamese category mapping'},
 {'acceptance': '- [ ] VI edit tests',
  'dependencies': 'v-05-vietnamese-edit-phrases.md',
  'effort': 'M',
  'id': 'L-05',
  'in_scope': 'VI edit regex.',
  'out_scope': '—',
  'phase': '0.5',
  'priority': 'Must',
  'proposal': 'Webhook edit tests VI.',
  'refs': 'L-05, V-5',
  'related': 'v-05-vietnamese-edit-phrases.md',
  'risks': '—',
  'slug': 'l-05-vietnamese-edit-phrases',
  'status': 'Planned',
  'summary': 'sửa thành 60k style edits.',
  'title': 'Vietnamese edit phrases'},
 {'acceptance': '- [ ] No EN in vi hot path',
  'dependencies': 'v-08-vietnamese-bot-templates.md',
  'effort': 'M',
  'id': 'L-06',
  'in_scope': 'VI templates for vi.',
  'out_scope': 'LLM replies',
  'phase': '0.5',
  'priority': 'Must',
  'proposal': 'V-8 template module by locale.',
  'refs': 'L-06, V-8',
  'related': 'v-08-vietnamese-bot-templates.md',
  'risks': '—',
  'slug': 'l-06-vietnamese-bot-templates',
  'status': 'Planned',
  'summary': 'All hot-path bot strings locale-aware.',
  'title': 'Vietnamese bot templates'},
 {'acceptance': '- [ ] Core UI VI',
  'dependencies': 'F-5',
  'effort': 'L',
  'id': 'L-07',
  'in_scope': 'VI UI strings priority list.',
  'out_scope': 'next-intl everywhere',
  'phase': '0.5–1',
  'priority': 'Should',
  'proposal': 'Phase 0.5 chat first; Phase 1 F-5 labels.',
  'refs': 'L-07, V-9, F-5',
  'related': 'v-09-vietnamese-welcome-examples.md, db-08-vietnamese-category-labels.md',
  'risks': 'Defer buttons briefly OK',
  'slug': 'l-07-vietnamese-ui',
  'status': 'Planned',
  'summary': 'Dashboard and settings in Vietnamese.',
  'title': 'Vietnamese UI (dashboard, settings)'},
 {'acceptance': '- [ ] locale persisted',
  'dependencies': 'v-10-locale-on-profile.md',
  'effort': 'S',
  'id': 'L-08',
  'in_scope': 'locale vi|en.',
  'out_scope': '—',
  'phase': '0.5',
  'priority': 'Should',
  'proposal': 'V-10 optional locale column.',
  'refs': 'L-08, V-10',
  'related': 'v-10-locale-on-profile.md, st-05-language-locale-preference.md',
  'risks': '—',
  'slug': 'l-08-locale-on-profile',
  'status': 'Planned',
  'summary': 'Profile locale drives templates.',
  'title': 'locale field on profile'},
 {'acceptance': '- [ ] All 5 steps pass',
  'dependencies': 'Phase 0.5',
  'effort': 'M',
  'id': 'L-09',
  'in_scope': '5-step golden flow.',
  'out_scope': '—',
  'phase': '0.5',
  'priority': 'Must',
  'proposal': 'vi-golden.spec.ts per PRODUCT_PLAN.',
  'refs': 'L-09',
  'related': 'tc-09-vietnamese-expense-chat.md',
  'risks': 'Flaky router',
  'slug': 'l-09-vietnamese-e2e-golden',
  'status': 'Planned',
  'summary': 'Playwright golden flow all Vietnamese steps.',
  'title': 'Vietnamese E2E golden flow'},
 {'acceptance': '- [x] EN E2E nightly',
  'dependencies': 'tests',
  'effort': 'S',
  'id': 'L-10',
  'in_scope': 'EN regression suite.',
  'out_scope': '—',
  'phase': 'MVP',
  'priority': 'Should',
  'proposal': 'utterances.jsonl + EN E2E nightly.',
  'refs': 'L-10',
  'related': 'eq-04-playwright-e2e-english.md',
  'risks': 'VI may break EN if careless',
  'slug': 'l-10-english-parity',
  'status': 'Partial',
  'summary': 'English flows stay green as VI added.',
  'title': 'English parity maintained'},
 {'acceptance': 'TBD',
  'dependencies': '—',
  'effort': 'L',
  'id': 'L-11',
  'in_scope': 'N/A',
  'out_scope': 'Premature framework',
  'phase': '5',
  'priority': "Won't (now)",
  'proposal': 'Defer until second locale beyond vi/en.',
  'refs': 'L-11',
  'related': 'st-05-language-locale-preference.md',
  'risks': 'Over-engineering',
  'slug': 'l-11-full-i18n-framework',
  'status': 'Future',
  'summary': 'next-intl for every string.',
  'title': 'Full i18n framework'},
 {'acceptance': '- [ ] ≥95% hybrid on VI subset',
  'dependencies': 'router',
  'effort': 'M',
  'id': 'V-1',
  'in_scope': 'Per-intent VI samples.',
  'out_scope': '—',
  'phase': '0.5',
  'priority': 'Must',
  'proposal': 'utterances-vi.jsonl + router_routes.yaml samples.',
  'refs': 'V-1',
  'related': 'l-01-vietnamese-intent-routing.md',
  'risks': 'Eval CI job',
  'slug': 'v-01-vietnamese-utterance-bank',
  'status': 'Planned',
  'summary': '8–15 phrases per intent in utterances + routes.',
  'title': 'Vietnamese utterance bank'},
 {'acceptance': '- [ ] VI pending tests',
  'dependencies': 'pending handler',
  'effort': 'M',
  'id': 'V-2',
  'in_scope': 'VI short replies.',
  'out_scope': '—',
  'phase': '0.5',
  'priority': 'Must',
  'proposal': 'Extend pending regex + keyword fallbacks.',
  'refs': 'V-2',
  'related': 'pm-10-vietnamese-pending-actions.md',
  'risks': '—',
  'slug': 'v-02-vietnamese-pending-replies',
  'status': 'Planned',
  'summary': 'xác nhận, hủy, sửa, đổi keywords.',
  'title': 'Vietnamese pending replies'},
 {'acceptance': '- [ ] Appendix B tests',
  'dependencies': 'rules.py',
  'effort': 'M',
  'id': 'V-3',
  'in_scope': 'Appendix B amounts.',
  'out_scope': 'FX',
  'phase': '0.5',
  'priority': 'Must',
  'proposal': 'parse_amount + test_extract_rules.',
  'refs': 'V-3',
  'related': 'tc-11-vnd-amount-formats.md',
  'risks': 'triệu vs tr',
  'slug': 'v-03-vnd-amount-parsing',
  'status': 'Planned',
  'summary': '50k, triệu, 500.000đ patterns.',
  'title': 'Vietnamese amount parsing'},
 {'acceptance': '- [ ] Hint unit tests',
  'dependencies': 'rules',
  'effort': 'M',
  'id': 'V-4',
  'in_scope': 'VI category tokens.',
  'out_scope': 'Custom taxonomy',
  'phase': '0.5',
  'priority': 'Must',
  'proposal': 'Hint map to normalized slugs.',
  'refs': 'V-4',
  'related': 'l-04-vietnamese-category-mapping.md',
  'risks': '—',
  'slug': 'v-04-vietnamese-category-hints',
  'status': 'Planned',
  'summary': 'ăn uống, lương, tiền nhà hints.',
  'title': 'Vietnamese category hints'},
 {'acceptance': '- [ ] VI edit webhook tests',
  'dependencies': 'pending',
  'effort': 'M',
  'id': 'V-5',
  'in_scope': 'VI edit patterns.',
  'out_scope': '—',
  'phase': '0.5',
  'priority': 'Must',
  'proposal': 'Webhook edit tests Vietnamese.',
  'refs': 'V-5',
  'related': 'pm-10-vietnamese-pending-actions.md',
  'risks': '—',
  'slug': 'v-05-vietnamese-edit-phrases',
  'status': 'Planned',
  'summary': 'sửa thành 60k, đổi danh mục.',
  'title': 'Vietnamese edit phrases'},
 {'acceptance': '- [ ] Bootstrap defaults',
  'dependencies': 'schema',
  'effort': 'S',
  'id': 'V-6',
  'in_scope': 'Default currency and TZ.',
  'out_scope': '—',
  'phase': '0.5',
  'priority': 'Must',
  'proposal': 'schema.py bootstrap defaults.',
  'refs': 'V-6',
  'related': 'st-04-vnd-hcm-defaults.md',
  'risks': '—',
  'slug': 'v-06-vnd-default-profile',
  'status': 'Planned',
  'summary': 'Seed VND and Asia/Ho_Chi_Minh for local user.',
  'title': 'Default profile VND + Ho Chi Minh'},
 {'acceptance': '- [ ] VI eval workflow',
  'dependencies': 'runbook',
  'effort': 'S',
  'id': 'V-7',
  'in_scope': 'VI accuracy gate.',
  'out_scope': 'Keyword-only for VI',
  'phase': '0.5',
  'priority': 'Must',
  'proposal': 'router-eval for utterances-vi.jsonl.',
  'refs': 'V-7',
  'related': 'eng-semantic-router.md',
  'risks': 'Speed vs accuracy',
  'slug': 'v-07-hybrid-router-vi-eval',
  'status': 'Planned',
  'summary': 'Document hybrid; CI VI eval job separate from keyword.',
  'title': 'Hybrid router required for Vietnamese'},
 {'acceptance': '- [ ] vi locale strings',
  'dependencies': 'templates',
  'effort': 'M',
  'id': 'V-8',
  'in_scope': 'All hot-path templates.',
  'out_scope': 'LLM copy',
  'phase': '0.5',
  'priority': 'Must',
  'proposal': 'Locale-aware template strings module.',
  'refs': 'V-8',
  'related': 'l-06-vietnamese-bot-templates.md',
  'risks': '—',
  'slug': 'v-08-vietnamese-bot-templates',
  'status': 'Planned',
  'summary': 'Record, confirm, report, error strings in VI.',
  'title': 'Vietnamese bot templates'},
 {'acceptance': '- [ ] VI welcome visible',
  'dependencies': 'ChatWorkspace',
  'effort': 'S',
  'id': 'V-9',
  'in_scope': 'Welcome + placeholder.',
  'out_scope': 'Full UI',
  'phase': '0.5',
  'priority': 'Must',
  'proposal': 'Copy update when locale=vi.',
  'refs': 'V-9',
  'related': 'ux-02-welcome-vietnamese.md',
  'risks': '—',
  'slug': 'v-09-vietnamese-welcome-examples',
  'status': 'Planned',
  'summary': 'ChatWorkspace welcome and placeholder VI.',
  'title': 'Vietnamese welcome + examples'},
 {'acceptance': '- [ ] locale=vi works',
  'dependencies': 'profile schema',
  'effort': 'S',
  'id': 'V-10',
  'in_scope': 'locale field + selection.',
  'out_scope': 'i18n framework',
  'phase': '0.5',
  'priority': 'Should',
  'proposal': 'Optional locale column on profile.',
  'refs': 'V-10',
  'related': 'l-08-locale-on-profile.md, st-05-language-locale-preference.md',
  'risks': '—',
  'slug': 'v-10-locale-on-profile',
  'status': 'Planned',
  'summary': 'vi default; templates by locale; EN fallback.',
  'title': 'locale on profile'},
 {'acceptance': 'TBD',
  'dependencies': 'budgets service',
  'effort': 'L',
  'id': 'BG-01',
  'in_scope': 'Set budget intent.',
  'out_scope': 'Rollover',
  'phase': '2',
  'priority': 'Should',
  'proposal': 'Phase 2 B-1 new dialogue flow.',
  'refs': 'BG-01, B-1',
  'related': 'eng-burr-fsm.md',
  'risks': '7th flow',
  'slug': 'bg-01-set-budget-chat',
  'status': 'Planned',
  'summary': 'Budget 2M for food this month in chat.',
  'title': 'Set monthly category budget (chat)'},
 {'acceptance': 'TBD',
  'dependencies': 'B-2',
  'effort': 'M',
  'id': 'BG-02',
  'in_scope': 'Budget status in chat.',
  'out_scope': '—',
  'phase': '2',
  'priority': 'Should',
  'proposal': 'Template budget remaining query.',
  'refs': 'BG-02, B-2',
  'related': 'bg-01-set-budget-chat.md',
  'risks': '—',
  'slug': 'bg-02-budget-status-chat',
  'status': 'Planned',
  'summary': 'How much left for dining.',
  'title': 'Check budget status (chat)'},
 {'acceptance': 'TBD',
  'dependencies': 'B-3',
  'effort': 'M',
  'id': 'BG-03',
  'in_scope': 'Progress UI.',
  'out_scope': '—',
  'phase': '2',
  'priority': 'Should',
  'proposal': 'Dashboard bars after B-1 data.',
  'refs': 'BG-03, B-3',
  'related': 'db-09-budget-progress-bars.md',
  'risks': '—',
  'slug': 'bg-03-budget-bars-dashboard',
  'status': 'Planned',
  'summary': 'Visual progress vs budget.',
  'title': 'Budget bars on dashboard'},
 {'acceptance': 'TBD',
  'dependencies': 'B-4',
  'effort': 'M',
  'id': 'BG-04',
  'in_scope': 'Threshold messages.',
  'out_scope': 'Push notifications',
  'phase': '2',
  'priority': 'Could',
  'proposal': 'Soft alerts in chat templates.',
  'refs': 'BG-04, B-4',
  'related': 'mb-03-push-budget-alert.md',
  'risks': '—',
  'slug': 'bg-04-budget-alerts',
  'status': 'Planned',
  'summary': 'Template alert on confirm or query.',
  'title': 'Alert at 80% / 100% budget'},
 {'acceptance': 'TBD',
  'dependencies': '—',
  'effort': 'L',
  'id': 'BG-05',
  'in_scope': 'N/A',
  'out_scope': '—',
  'phase': '—',
  'priority': 'Could',
  'proposal': 'Defer post-budgets.',
  'refs': 'BG-05',
  'related': 'bg-01-set-budget-chat.md',
  'risks': '—',
  'slug': 'bg-05-savings-goals',
  'status': 'Future',
  'summary': 'Save 10M for trip.',
  'title': 'Savings goals'},
 {'acceptance': 'TBD',
  'dependencies': 'bg-01-set-budget-chat.md',
  'effort': 'M',
  'id': 'BG-06',
  'in_scope': 'N/A',
  'out_scope': '—',
  'phase': '—',
  'priority': 'Could',
  'proposal': 'Defer.',
  'refs': 'BG-06',
  'related': 'bg-01-set-budget-chat.md',
  'risks': 'Accounting complexity',
  'slug': 'bg-06-rollover-budget',
  'status': 'Future',
  'summary': 'Unused budget carries to next month.',
  'title': 'Rollover unused budget'},
 {'acceptance': 'TBD',
  'dependencies': 'R-1',
  'effort': 'L',
  'id': 'RC-01',
  'in_scope': 'Recurring definitions.',
  'out_scope': 'Bank sync',
  'phase': '3',
  'priority': 'Should',
  'proposal': 'Phase 3 R-1 recurring model.',
  'refs': 'RC-01, R-1',
  'related': 'rc-02-apply-due-recurring.md',
  'risks': '—',
  'slug': 'rc-01-recurring-templates',
  'status': 'Planned',
  'summary': 'Rent or salary monthly templates.',
  'title': 'Define recurring expense/income'},
 {'acceptance': 'TBD',
  'dependencies': 'R-2',
  'effort': 'M',
  'id': 'RC-02',
  'in_scope': 'Apply due command.',
  'out_scope': '—',
  'phase': '3',
  'priority': 'Should',
  'proposal': 'Batch pending from due items.',
  'refs': 'RC-02, R-2',
  'related': 'rc-01-recurring-templates.md',
  'risks': '—',
  'slug': 'rc-02-apply-due-recurring',
  'status': 'Planned',
  'summary': 'Apply recurring for this month in chat.',
  'title': 'Apply due recurring (confirm batch)'},
 {'acceptance': 'TBD',
  'dependencies': 'R-3',
  'effort': 'M',
  'id': 'RC-03',
  'in_scope': 'Opt-in auto-confirm.',
  'out_scope': '—',
  'phase': '3',
  'priority': 'Could',
  'proposal': 'Off by default flag.',
  'refs': 'RC-03, R-3',
  'related': 'rc-02-apply-due-recurring.md',
  'risks': 'Trust / errors',
  'slug': 'rc-03-auto-confirm-recurring',
  'status': 'Planned',
  'summary': 'Skip manual confirm for trusted recurring.',
  'title': 'Auto-confirm recurring (opt-in)'},
 {'acceptance': 'TBD',
  'dependencies': 'MB-03',
  'effort': 'L',
  'id': 'RC-04',
  'in_scope': 'N/A',
  'out_scope': '—',
  'phase': '—',
  'priority': 'Could',
  'proposal': 'Needs notification infra.',
  'refs': 'RC-04',
  'related': 'mb-03-push-budget-alert.md',
  'risks': '—',
  'slug': 'rc-04-recurring-reminders',
  'status': 'Future',
  'summary': 'Push or email when recurring due.',
  'title': 'Remind when recurring due'},
 {'acceptance': 'TBD',
  'dependencies': 'Phase 4',
  'effort': 'XL',
  'id': 'AU-01',
  'in_scope': 'Auth pages + session.',
  'out_scope': 'Social-only OAuth only',
  'phase': '4',
  'priority': 'Should',
  'proposal': '/login stub today; Phase 4 real auth.',
  'refs': 'AU-01',
  'related': 'au-04-postgres-migration.md',
  'risks': 'Scope XL',
  'slug': 'au-01-login-signup',
  'status': 'Partial',
  'summary': 'Secure access to hosted app.',
  'title': 'Login / signup'},
 {'acceptance': 'TBD',
  'dependencies': 'Postgres',
  'effort': 'XL',
  'id': 'AU-02',
  'in_scope': 'Per-user data partition.',
  'out_scope': 'Shared local user',
  'phase': '4',
  'priority': 'Must (hosted)',
  'proposal': 'RLS + user_id on all queries.',
  'refs': 'AU-02, U-3',
  'related': 'au-04-postgres-migration.md',
  'risks': 'Migration',
  'slug': 'au-02-multi-user-isolation',
  'status': 'Future',
  'summary': 'Each user sees only own data.',
  'title': 'Multi-user data isolation'},
 {'acceptance': 'TBD',
  'dependencies': 'runbook',
  'effort': 'L',
  'id': 'AU-03',
  'in_scope': 'Deploy pipeline.',
  'out_scope': '—',
  'phase': '4',
  'priority': 'Should',
  'proposal': 'Execute production-deploy.md when ready.',
  'refs': 'AU-03',
  'related': 'au-07-private-backend-network.md',
  'risks': 'Ops burden',
  'slug': 'au-03-hosted-production-deploy',
  'status': 'Partial',
  'summary': 'Vercel + backend VPS runbook.',
  'title': 'Hosted production deploy'},
 {'acceptance': 'TBD',
  'dependencies': 'Phase 4',
  'effort': 'XL',
  'id': 'AU-04',
  'in_scope': 'Postgres primary DB.',
  'out_scope': 'SQLite hosted prod',
  'phase': '4',
  'priority': 'Must (hosted)',
  'proposal': 'Migrate schema + queries from SQLite.',
  'refs': 'AU-04, U-2',
  'related': 'ds-07-cloud-sync.md',
  'risks': 'Data migration',
  'slug': 'au-04-postgres-migration',
  'status': 'Planned',
  'summary': 'Multi-user OLTP on Postgres.',
  'title': 'Postgres instead of SQLite'},
 {'acceptance': 'TBD',
  'dependencies': 'archive',
  'effort': 'L',
  'id': 'AU-05',
  'in_scope': 'RLS policies.',
  'out_scope': '—',
  'phase': '4',
  'priority': 'Must (hosted)',
  'proposal': 'Reference archive/supabase patterns.',
  'refs': 'AU-05',
  'related': 'au-02-multi-user-isolation.md',
  'risks': '—',
  'slug': 'au-05-service-role-rls',
  'status': 'Future',
  'summary': 'Supabase-style RLS from archive.',
  'title': 'Service-role / RLS patterns'},
 {'acceptance': 'TBD',
  'dependencies': 'au-01-login-signup.md',
  'effort': 'M',
  'id': 'AU-06',
  'in_scope': 'N/A',
  'out_scope': '—',
  'phase': '4',
  'priority': 'Could',
  'proposal': 'Defer with auth.',
  'refs': 'AU-06',
  'related': 'au-01-login-signup.md',
  'risks': '—',
  'slug': 'au-06-forgot-password',
  'status': 'Future',
  'summary': 'Account recovery flow.',
  'title': 'Forgot password'},
 {'acceptance': 'TBD',
  'dependencies': 'Phase 4',
  'effort': 'M',
  'id': 'AU-07',
  'in_scope': 'Private chat backend.',
  'out_scope': 'Public webhook',
  'phase': '4',
  'priority': 'Must (hosted)',
  'proposal': 'ADR-003 network layout.',
  'refs': 'AU-07, U-5',
  'related': 'au-03-hosted-production-deploy.md',
  'risks': '—',
  'slug': 'au-07-private-backend-network',
  'status': 'Planned',
  'summary': 'Webhook not public internet.',
  'title': 'Private backend network'},
 {'acceptance': 'TBD',
  'dependencies': 'ux-05-rate-limit-message.md',
  'effort': 'M',
  'id': 'AU-08',
  'in_scope': 'Distributed 429.',
  'out_scope': 'Single-node limit OK now',
  'phase': '4',
  'priority': 'Should (scale)',
  'proposal': 'When scaling beyond single node.',
  'refs': 'AU-08, U-4',
  'related': 'ux-05-rate-limit-message.md',
  'risks': 'Cost',
  'slug': 'au-08-distributed-rate-limiting',
  'status': 'Planned',
  'summary': 'Redis/Upstash rate limits multi-instance.',
  'title': 'Distributed rate limiting'},
 {'acceptance': 'TBD',
  'dependencies': '—',
  'effort': 'M',
  'id': 'MB-01',
  'in_scope': 'N/A',
  'out_scope': '—',
  'phase': '—',
  'priority': 'Could',
  'proposal': 'Defer; archive prototype options.',
  'refs': 'MB-01',
  'related': 'mb-02-native-mobile-app.md',
  'risks': '—',
  'slug': 'mb-01-pwa-install',
  'status': 'Future',
  'summary': 'Add to home screen.',
  'title': 'Install as PWA'},
 {'acceptance': 'TBD',
  'dependencies': '—',
  'effort': 'XL',
  'id': 'MB-02',
  'in_scope': 'N/A',
  'out_scope': '—',
  'phase': '5',
  'priority': 'Could',
  'proposal': 'Phase 5 / archive.',
  'refs': 'MB-02',
  'related': 'tc-12-receipt-photo-capture.md',
  'risks': 'Maintenance',
  'slug': 'mb-02-native-mobile-app',
  'status': 'Future',
  'summary': 'Expo or React Native app.',
  'title': 'Native iOS / Android app'},
 {'acceptance': 'TBD',
  'dependencies': 'bg-04-budget-alerts.md',
  'effort': 'L',
  'id': 'MB-03',
  'in_scope': 'N/A',
  'out_scope': '—',
  'phase': '—',
  'priority': 'Could',
  'proposal': 'Needs native or PWA push.',
  'refs': 'MB-03',
  'related': 'bg-04-budget-alerts.md',
  'risks': '—',
  'slug': 'mb-03-push-budget-alert',
  'status': 'Future',
  'summary': 'Mobile alert on budget threshold.',
  'title': 'Push notification (budget alert)'},
 {'acceptance': 'TBD',
  'dependencies': 'ds-02-chat-history-browser.md',
  'effort': 'L',
  'id': 'MB-04',
  'in_scope': 'N/A',
  'out_scope': '—',
  'phase': '—',
  'priority': 'Could',
  'proposal': 'Local-first queue on reconnect.',
  'refs': 'MB-04',
  'related': '—',
  'risks': 'Sync conflicts',
  'slug': 'mb-04-offline-chat-queue',
  'status': 'Future',
  'summary': 'Record transactions without network.',
  'title': 'Offline chat queue'},
 {'acceptance': '- [ ] Usable on 375px',
  'dependencies': 'CSS',
  'effort': 'M',
  'id': 'MB-05',
  'in_scope': 'Basic responsive chat.',
  'out_scope': 'Native app',
  'phase': 'MVP',
  'priority': 'Should',
  'proposal': 'Improve responsive layout pass.',
  'refs': 'MB-05',
  'related': '—',
  'risks': 'Not primary design',
  'slug': 'mb-05-responsive-mobile-web',
  'status': 'Partial',
  'summary': 'Usable on phone browser.',
  'title': 'Responsive mobile web'},
 {'acceptance': 'TBD',
  'dependencies': '—',
  'effort': 'XL',
  'id': 'IN-01',
  'in_scope': 'N/A',
  'out_scope': '—',
  'phase': '—',
  'priority': 'Could',
  'proposal': 'Defer indefinitely.',
  'refs': 'IN-01',
  'related': 'tc-14-bulk-import-csv.md',
  'risks': 'Compliance',
  'slug': 'in-01-bank-feed',
  'status': 'Future',
  'summary': 'Auto-import from bank.',
  'title': 'Bank feed / open banking'},
 {'acceptance': 'TBD',
  'dependencies': '—',
  'effort': 'L',
  'id': 'IN-02',
  'in_scope': 'N/A',
  'out_scope': '—',
  'phase': '—',
  'priority': 'Could',
  'proposal': 'PRODUCT_PLAN rank 10 defer.',
  'refs': 'IN-02',
  'related': '—',
  'risks': '—',
  'slug': 'in-02-split-transaction',
  'status': 'Future',
  'summary': 'Shared bill with friends.',
  'title': 'Split transaction'},
 {'acceptance': 'TBD',
  'dependencies': 'st-02-currency-setting.md',
  'effort': 'L',
  'id': 'IN-03',
  'in_scope': 'N/A',
  'out_scope': 'FX tables',
  'phase': '—',
  'priority': 'Could',
  'proposal': 'Single profile currency today.',
  'refs': 'IN-03',
  'related': '—',
  'risks': '—',
  'slug': 'in-03-multi-currency-tx',
  'status': 'Future',
  'summary': 'USD expense on VND account.',
  'title': 'Multi-currency transactions'},
 {'acceptance': 'TBD',
  'dependencies': '—',
  'effort': 'M',
  'id': 'IN-04',
  'in_scope': 'N/A',
  'out_scope': '—',
  'phase': '—',
  'priority': 'Could',
  'proposal': 'Defer.',
  'refs': 'IN-04',
  'related': '—',
  'risks': '—',
  'slug': 'in-04-tags-labels',
  'status': 'Future',
  'summary': '#vacation tags on transactions.',
  'title': 'Tags / labels beyond category'},
 {'acceptance': 'TBD',
  'dependencies': 'cm-04-transaction-list-ui.md',
  'effort': 'M',
  'id': 'IN-05',
  'in_scope': 'N/A',
  'out_scope': '—',
  'phase': '—',
  'priority': 'Could',
  'proposal': 'Defer until list UI + index.',
  'refs': 'IN-05',
  'related': '—',
  'risks': '—',
  'slug': 'in-05-search-full-text',
  'status': 'Future',
  'summary': 'Find starbucks in history.',
  'title': 'Search full-text history'},
 {'acceptance': 'N/A',
  'dependencies': '—',
  'effort': '—',
  'id': 'IN-06',
  'in_scope': 'N/A',
  'out_scope': '—',
  'phase': '—',
  'priority': "Won't",
  'proposal': 'Reject per ROADMAP non-goals.',
  'refs': 'IN-06',
  'related': 'oos-langgraph-agents.md',
  'risks': 'Safety',
  'slug': 'in-06-agent-tools-every-turn',
  'status': 'Out of scope',
  'summary': 'Autonomous PF agent.',
  'title': 'Agent with tools every turn'},
 {'acceptance': 'TBD',
  'dependencies': 'eng-vllm-local-llm.md',
  'effort': 'L',
  'id': 'IN-07',
  'in_scope': 'Optional local extract.',
  'out_scope': 'Mandatory local',
  'phase': '5',
  'priority': "Won't (now)",
  'proposal': 'eng-vllm-local-llm when cloud stable.',
  'refs': 'IN-07',
  'related': 'eng-vllm-local-llm.md',
  'risks': 'GPU ops',
  'slug': 'in-07-local-llm-vllm',
  'status': 'Roadmap',
  'summary': 'Privacy / no cloud LLM.',
  'title': 'Local LLM extraction (vLLM)'},
 {'acceptance': 'TBD',
  'dependencies': 'eng-outlines-structured-extract.md',
  'effort': 'M',
  'id': 'IN-08',
  'in_scope': 'Stricter schema enforce.',
  'out_scope': '—',
  'phase': '5',
  'priority': "Won't (now)",
  'proposal': 'eng-outlines-structured-extract optional.',
  'refs': 'IN-08',
  'related': 'eng-outlines-structured-extract.md, tc-08-llm-extract-fallback.md',
  'risks': '—',
  'slug': 'in-08-outlines-structured-json',
  'status': 'Roadmap',
  'summary': 'Replace raw Gemini JSON.',
  'title': 'Outlines for stricter JSON'},
 {'acceptance': '- [x] /health',
  'dependencies': 'health route',
  'effort': '—',
  'id': 'EQ-01',
  'in_scope': '/health returns OK.',
  'out_scope': '—',
  'phase': 'MVP',
  'priority': 'Must',
  'proposal': 'Maintain health endpoint + smoke scripts.',
  'refs': 'EQ-01',
  'related': 'ux-04-error-retry.md',
  'risks': '—',
  'slug': 'eq-01-health-check',
  'status': 'Shipped',
  'summary': 'App detects backend outage via /health.',
  'title': 'Chat backend health check'},
 {'acceptance': '- [x] test_session_persist',
  'dependencies': 'eng-sqlite-sessions.md',
  'effort': '—',
  'id': 'EQ-02',
  'in_scope': 'Session persist tests.',
  'out_scope': '—',
  'phase': 'P2',
  'priority': 'Must',
  'proposal': 'SQLite chat_sessions (shipped P2).',
  'refs': 'EQ-02',
  'related': 'pm-11-pending-survives-restart.md',
  'risks': '—',
  'slug': 'eq-02-session-survives-restart',
  'status': 'Shipped',
  'summary': 'Pending not lost on restart.',
  'title': 'Session survives restart'},
 {'acceptance': '- [x] Test suites green',
  'dependencies': 'CI',
  'effort': '—',
  'id': 'EQ-03',
  'in_scope': '86+ pytest, 67+ Vitest.',
  'out_scope': '—',
  'phase': 'MVP',
  'priority': 'Must',
  'proposal': 'Maintain coverage; expand VI tests.',
  'refs': 'EQ-03',
  'related': 'eq-05-vietnamese-e2e.md',
  'risks': '—',
  'slug': 'eq-03-automated-regression-tests',
  'status': 'Shipped',
  'summary': 'pytest + Vitest guard regressions.',
  'title': 'Automated regression tests'},
 {'acceptance': '- [x] nightly CI',
  'dependencies': 'Playwright',
  'effort': '—',
  'id': 'EQ-04',
  'in_scope': 'CP-1–CP-6 English.',
  'out_scope': '—',
  'phase': '0',
  'priority': 'Must',
  'proposal': 'e2e-nightly.yml.',
  'refs': 'EQ-04',
  'related': 'eq-05-vietnamese-e2e.md',
  'risks': '—',
  'slug': 'eq-04-playwright-e2e-english',
  'status': 'Shipped',
  'summary': 'Critical English paths in Playwright.',
  'title': 'Playwright E2E (English)'},
 {'acceptance': '- [ ] VI E2E in CI',
  'dependencies': 'l-09-vietnamese-e2e-golden.md',
  'effort': 'M',
  'id': 'EQ-05',
  'in_scope': 'VI golden spec.',
  'out_scope': '—',
  'phase': '0.5',
  'priority': 'Must',
  'proposal': 'vi-golden Playwright after Phase 0.5.',
  'refs': 'EQ-05',
  'related': 'l-09-vietnamese-e2e-golden.md',
  'risks': 'Flaky if router weak',
  'slug': 'eq-05-vietnamese-e2e',
  'status': 'Planned',
  'summary': 'Locale regressions caught in CI.',
  'title': 'Playwright E2E (Vietnamese)'},
 {'acceptance': 'TBD',
  'dependencies': 'eng-burr-fsm.md',
  'effort': 'L',
  'id': 'EQ-06',
  'in_scope': 'Burr graph.',
  'out_scope': 'Premature Burr',
  'phase': '5',
  'priority': "Won't (now)",
  'proposal': 'eng-burr-fsm when 7th flow.',
  'refs': 'EQ-06, P3',
  'related': 'eng-burr-fsm.md, bg-01-set-budget-chat.md',
  'risks': 'New dependency',
  'slug': 'eq-06-burr-fsm-complex-flows',
  'status': 'Roadmap',
  'summary': 'Maintainable dialogue when flows multiply.',
  'title': 'Burr FSM for complex flows'},
 {'acceptance': 'TBD',
  'dependencies': 'eng-duckdb-analytics.md',
  'effort': 'L',
  'id': 'EQ-07',
  'in_scope': 'DuckDB read path.',
  'out_scope': '—',
  'phase': '5',
  'priority': "Won't (now)",
  'proposal': 'eng-duckdb-analytics when slow.',
  'refs': 'EQ-07, P4',
  'related': 'eng-duckdb-analytics.md, rq-12-fast-analytics-scale.md',
  'risks': '—',
  'slug': 'eq-07-duckdb-fast-reports',
  'status': 'Roadmap',
  'summary': 'Large history fast aggregations.',
  'title': 'DuckDB fast reports'},
 {'acceptance': 'TBD',
  'dependencies': 'schema migration',
  'effort': 'L',
  'id': 'AC-01',
  'in_scope': 'CRUD accounts, default account, tx.account_id.',
  'out_scope': 'Full open banking.',
  'phase': '1.5',
  'priority': 'Should',
  'proposal': 'Accounts table + optional account on record; chat mention later.',
  'refs': 'AC-01',
  'related': 'ac-04-spending-by-account-report.md',
  'risks': 'Scope vs Phase 0.5',
  'slug': 'ac-01-payment-accounts-mvp',
  'status': 'Planned',
  'summary': 'Track cash, bank, e-wallet accounts; assign txs to account.',
  'title': 'Payment accounts MVP'},
 {'acceptance': 'TBD',
  'dependencies': 'ac-01-payment-accounts-mvp.md',
  'effort': 'M',
  'id': 'AC-02',
  'in_scope': 'Internal transfers.',
  'out_scope': 'External payments',
  'phase': '1.5',
  'priority': 'Should',
  'proposal': 'Transfer pair transactions or transfer type.',
  'refs': 'AC-02',
  'related': 'ac-01-payment-accounts-mvp.md',
  'risks': 'Double-entry',
  'slug': 'ac-02-account-transfers',
  'status': 'Planned',
  'summary': 'Transfer between own accounts without affecting net worth.',
  'title': 'Account transfers'},
 {'acceptance': 'TBD',
  'dependencies': 'ac-01-payment-accounts-mvp.md',
  'effort': 'L',
  'id': 'AC-03',
  'in_scope': 'CC balance tracking.',
  'out_scope': 'Rewards points',
  'phase': '2',
  'priority': 'Could',
  'proposal': 'Card account type + payment from cash.',
  'refs': 'AC-03',
  'related': 'ac-01-payment-accounts-mvp.md',
  'risks': 'Complexity',
  'slug': 'ac-03-credit-card-liability',
  'status': 'Planned',
  'summary': 'Credit card as liability account with payment flows.',
  'title': 'Credit card liability'},
 {'acceptance': 'TBD',
  'dependencies': 'ac-01-payment-accounts-mvp.md',
  'effort': 'M',
  'id': 'AC-04',
  'in_scope': 'Chat + dashboard by account.',
  'out_scope': '—',
  'phase': '1.5',
  'priority': 'Should',
  'proposal': 'Template report by account_id.',
  'refs': 'AC-04',
  'related': 'rq-02-spending-total-period.md, ac-01-payment-accounts-mvp.md',
  'risks': '—',
  'slug': 'ac-04-spending-by-account-report',
  'status': 'Planned',
  'summary': 'How much spent from each account this month.',
  'title': 'Spending by account report'},
 {'acceptance': '- [x] P1 shipped',
  'dependencies': 'router',
  'effort': '—',
  'id': 'ENG-SR',
  'in_scope': 'Semantic + keyword routes.',
  'out_scope': 'LLM routing',
  'phase': 'P1',
  'priority': 'Must',
  'proposal': 'Maintain ≥95% utterances.jsonl hybrid locally.',
  'refs': 'ROADMAP P1',
  'related': 'v-07-hybrid-router-vi-eval.md',
  'risks': 'Keyword CI ≠ hybrid',
  'slug': 'eng-semantic-router',
  'status': 'Shipped',
  'summary': 'Layer-1 intent routing with ROUTER_MODE hybrid.',
  'title': 'Semantic Router + hybrid fallback'},
 {'acceptance': '- [x] P2 shipped',
  'dependencies': 'extract',
  'effort': '—',
  'id': 'ENG-GEM',
  'in_scope': 'CompositeFieldExtractor.',
  'out_scope': 'LLM every message',
  'phase': 'P2',
  'priority': 'Should',
  'proposal': 'Keep LLM_EXTRACT_ENABLED off by default.',
  'refs': 'ROADMAP P2',
  'related': 'tc-08-llm-extract-fallback.md',
  'risks': 'SDK deprecation',
  'slug': 'eng-gemini-extraction',
  'status': 'Shipped',
  'summary': 'Rules-first Gemini gap-fill for extract.',
  'title': 'Gemini JSON extraction'},
 {'acceptance': '- [x] test_session_persist',
  'dependencies': 'sessions',
  'effort': '—',
  'id': 'ENG-SES',
  'in_scope': 'Session persist.',
  'out_scope': 'Postgres sessions',
  'phase': 'P2',
  'priority': 'Must',
  'proposal': 'Maintain chat_sessions table.',
  'refs': 'ROADMAP P2',
  'related': 'pm-11-pending-survives-restart.md',
  'risks': '—',
  'slug': 'eng-sqlite-sessions',
  'status': 'Shipped',
  'summary': 'Persist dialogue phase and pending across restarts.',
  'title': 'SQLite chat_sessions persistence'},
 {'acceptance': 'TBD',
  'dependencies': 'Burr',
  'effort': 'L',
  'id': 'ENG-BURR',
  'in_scope': 'Burr graph, same payloads.',
  'out_scope': 'Big-bang rewrite',
  'phase': '5',
  'priority': "Won't (now)",
  'proposal': 'Start when 7th flow or brittle handlers.',
  'refs': 'ROADMAP P3',
  'related': 'eq-06-burr-fsm-complex-flows.md, eng-burr-debug-ui.md',
  'risks': 'Learning curve',
  'slug': 'eng-burr-fsm',
  'status': 'Roadmap',
  'summary': 'Replace/wrap dialogue/engine.py with Burr graph.',
  'title': 'Burr FSM for dialogue'},
 {'acceptance': 'TBD',
  'dependencies': 'eng-burr-fsm.md',
  'effort': 'S',
  'id': 'ENG-BURR-UI',
  'in_scope': 'Debug transitions locally.',
  'out_scope': '—',
  'phase': '5',
  'priority': 'Could',
  'proposal': 'Add when Burr P3 starts.',
  'refs': 'ROADMAP',
  'related': 'eng-burr-fsm.md',
  'risks': '—',
  'slug': 'eng-burr-debug-ui',
  'status': 'Roadmap',
  'summary': 'Burr UI in local dev runbook.',
  'title': 'Burr local UI / transition debugging'},
 {'acceptance': 'TBD',
  'dependencies': 'DuckDB',
  'effort': 'L',
  'id': 'ENG-DUCK',
  'in_scope': 'DuckDB read path.',
  'out_scope': 'DuckDB writes',
  'phase': '5',
  'priority': "Won't (now)",
  'proposal': 'When report endpoints slow.',
  'refs': 'ROADMAP P4',
  'related': 'eq-07-duckdb-fast-reports.md, rq-12-fast-analytics-scale.md',
  'risks': 'Ops',
  'slug': 'eng-duckdb-analytics',
  'status': 'Roadmap',
  'summary': 'Read-only columnar aggregations on finguard.db.',
  'title': 'DuckDB analytics on SQLite file'},
 {'acceptance': 'TBD',
  'dependencies': 'extract',
  'effort': 'M',
  'id': 'ENG-OUT',
  'in_scope': 'Outlines schema.',
  'out_scope': '—',
  'phase': '5',
  'priority': "Won't (now)",
  'proposal': 'Optional after Gemini stable.',
  'refs': 'ROADMAP',
  'related': 'in-08-outlines-structured-json.md, tc-08-llm-extract-fallback.md',
  'risks': '—',
  'slug': 'eng-outlines-structured-extract',
  'status': 'Roadmap',
  'summary': 'Stricter JSON than raw Gemini.',
  'title': 'Outlines structured extract'},
 {'acceptance': 'TBD',
  'dependencies': 'LLM',
  'effort': 'L',
  'id': 'ENG-VLLM',
  'in_scope': 'vLLM endpoint option.',
  'out_scope': '—',
  'phase': '5',
  'priority': "Won't (now)",
  'proposal': 'After cloud extract proven.',
  'refs': 'ROADMAP',
  'related': 'in-07-local-llm-vllm.md',
  'risks': 'GPU',
  'slug': 'eng-vllm-local-llm',
  'status': 'Roadmap',
  'summary': 'On-prem extraction without cloud.',
  'title': 'Local LLM via vLLM'},
 {'acceptance': 'N/A',
  'dependencies': '—',
  'effort': '—',
  'id': 'OOS-RQ11',
  'in_scope': 'Templates + SQL only.',
  'out_scope': 'LLM prose',
  'phase': '—',
  'priority': "Won't",
  'proposal': 'Permanently out of scope per ADR.',
  'refs': 'RQ-11, ROADMAP',
  'related': 'rq-11-llm-narrative-report.md',
  'risks': 'Trust/cost',
  'slug': 'oos-llm-report-prose',
  'status': 'Out of scope',
  'summary': 'Narrative finance summaries via LLM.',
  'title': 'LLM-generated report prose'},
 {'acceptance': 'N/A',
  'dependencies': '—',
  'effort': '—',
  'id': 'OOS-IN06',
  'in_scope': 'Deterministic confirm flows.',
  'out_scope': 'Agent loops',
  'phase': '—',
  'priority': "Won't",
  'proposal': 'Reject unless requirements change.',
  'refs': 'IN-06, ROADMAP',
  'related': 'in-06-agent-tools-every-turn.md',
  'risks': 'Safety',
  'slug': 'oos-langgraph-agents',
  'status': 'Out of scope',
  'summary': 'Autonomous agents on money flows.',
  'title': 'LangGraph / tool-calling agents'}]



def current_state(status: str) -> str:
    return STATUS_CURRENT.get(status, "Status documented in USE_CASE_CATALOG.")


def related_links(related: str) -> str:
    if not related or related.strip() in ("—", "-", "N/A"):
        return "—"
    parts = [s.strip() for s in related.split(",")]
    return ", ".join(
        f"[{p.replace('.md', '')}](./{p})" for p in parts if p
    )


def render_spec(f: dict[str, str]) -> str:
    return f"""# {f['title']}

| Field | Value |
|-------|-------|
| **Spec ID** | {f['id']} |
| **Status** | {f['status']} |
| **Phase** | {f['phase']} |
| **Priority** | {f['priority']} |
| **Effort** | {f['effort']} |
| **Catalog refs** | {f['refs']} |

---

## PO decision

| Option | Check |
|--------|-------|
| **Build** | [ ] |
| **Defer** | [ ] |
| **Reject** | [ ] |

**Decision date:** __________
**Notes:**

---

## Problem

{f['summary']}

## User stories

- As a user, I want this capability so I can manage personal finances through chat without spreadsheets.

## Current state

{current_state(f['status'])}

## Proposal

{f['proposal']}

## Scope

### In scope

{f['in_scope']}

### Out of scope

{f['out_scope']}

## Dependencies

{f['dependencies']}

## Acceptance criteria

{f['acceptance']}

## Risks

{f['risks']}

## Related

{related_links(f['related'])}

---

## References

- [USE_CASE_CATALOG](../USE_CASE_CATALOG.md)
- [PRODUCT_PLAN](../PRODUCT_PLAN.md)
- [ROADMAP](../ROADMAP.md)
"""


def category_for(f: dict[str, str]) -> str:
    slug = f["slug"]
    prefixes = (
        ("tc-", "Transaction capture"),
        ("pm-", "Pending management"),
        ("cm-", "Confirmed transactions"),
        ("rq-", "Reports & queries"),
        ("db-", "Dashboard & charts"),
        ("st-", "Settings & profile"),
        ("ds-", "Data storage & export"),
        ("ux-", "Chat UX"),
        ("l-", "Localization"),
        ("v-", "Phase 0.5 (Vietnamese)"),
        ("bg-", "Budgets & goals"),
        ("rc-", "Recurring"),
        ("au-", "Auth & deployment"),
        ("mb-", "Mobile & PWA"),
        ("in-", "Integrations"),
        ("eq-", "Quality & testing"),
        ("ac-", "Payment accounts"),
        ("eng-", "Engineering platform"),
        ("oos-", "Out of scope"),
    )
    for prefix, name in prefixes:
        if slug.startswith(prefix):
            return name
    return "Other"


def write_readme(features: list[dict[str, str]]) -> None:
    lines = [
        "# FinGuard feature specs",
        "",
        "One RFC-style spec per feature. Generated by `build_all_specs.py`.",
        "",
        "**Catalog:** [USE_CASE_CATALOG](../USE_CASE_CATALOG.md) · "
        "**Plan:** [PRODUCT_PLAN](../PRODUCT_PLAN.md) · "
        "**Roadmap:** [ROADMAP](../ROADMAP.md)",
        "",
        f"**Total specs:** {len(features)}",
        "",
        "## How to review (PO)",
        "",
        "1. Open a spec from the tables below (or search by ID, e.g. `V-1`, `TC-09`).",
        "2. Read **Problem**, **Proposal**, **Scope**, and **Acceptance criteria**.",
        "3. Check **Build**, **Defer**, or **Reject** in the **PO decision** section; add date and notes.",
        "4. For **Defer**, note target phase; for **Reject**, note why (duplicate, out of vision, etc.).",
        "5. Update [PRODUCT_PLAN](../PRODUCT_PLAN.md) phase backlog when you commit to a batch of **Build** decisions.",
        "",
        "**Suggested review order:** Phase **0.5** (V-* / TC-09–11 / PM-10 / RQ-07) → Phase **1** (CM-04+, DB-06+) → Phase **1.5** (AC-*) → Phase **2** (BG-*) → Future / Roadmap / Out of scope last.",
        "",
        "Regenerate after editing feature definitions in `build_all_specs.py`: "
        "`python docs/specs/build_all_specs.py` (re-run overwrites generated `.md` files).",
        "",
        "---",
        "",
    ]
    current_cat = None
    for f in features:
        cat = category_for(f)
        if cat != current_cat:
            if current_cat is not None:
                lines.append("")
            lines.extend([
                f"## {cat}",
                "",
                "| Spec ID | Title | Status | Phase | Priority | Effort | Spec file | Build decision |",
                "|---------|-------|--------|-------|----------|--------|-----------|----------------|",
            ])
            current_cat = cat
        lines.append(
            f"| {f['id']} | {f['title']} | {f['status']} | {f['phase']} | "
            f"{f['priority']} | {f['effort']} | [{f['slug']}.md](./{f['slug']}.md) | |"
        )
    lines.append("")
    (SPECS_DIR / "README.md").write_text("\n".join(lines) + "\n")


def main() -> None:
    for f in FEATURES:
        path = SPECS_DIR / f"{f['slug']}.md"
        path.write_text(render_spec(f))
    write_readme(FEATURES)
    print(f"Wrote {len(FEATURES)} spec files + README.md")


if __name__ == "__main__":
    main()
